// ══════════════════════════════════════════
// ICONOS SVG — logos originales (Comentados para uso futuro)
// ══════════════════════════════════════════
/*
const ICONS = {
  // ── VIDEO ──
  'After Effects': `<svg viewBox="0 0 44 44"><rect width="44" height="44" rx="9" fill="#00005b"/><text x="22" y="30" text-anchor="middle" font-family="Georgia,serif" font-weight="900" font-size="22" fill="#9999FF">Ae</text></svg>`,
  'Premiere Pro': `<svg viewBox="0 0 44 44"><rect width="44" height="44" rx="9" fill="#1d1342"/><text x="22" y="30" text-anchor="middle" font-family="Georgia,serif" font-weight="900" font-size="22" fill="#E8D5A3">Pr</text></svg>`,
  ... (Contenido omitido por brevedad, ver historial) ...
};
*/

// Ahora el sistema utiliza Simple Icons vía CDN para mayor consistencia y catálogo.
// Ver función getIcon() en app.js para la lógica de carga.

// ═══════════════════════════════════════════════════════════

// ═══════════════════════════════════════════════════════════
// CATEGORÍAS
// ═══════════════════════════════════════════════════════════
const CATEGORIES = [
  { id: 'all',         name: 'Todos los Programas',    icon: '🖥️' },
  { id: 'video',       name: 'Video / Post-producción', icon: '🎬' },
  { id: 'graphic',     name: 'Diseño y Arte Digital',   icon: '🎨' },
  { id: 'audio',       name: 'Producción de Audio',     icon: '🎵' },
  { id: '3d',          name: '3D y Animación',          icon: '🧊' },
  { id: 'engineering', name: 'Ingeniería y CAD',        icon: '⚙️' },
  { id: 'medicine',    name: 'Medicina y Estudio',      icon: '🩺' },
  { id: 'dev',         name: 'Sistemas / IT',           icon: '💻' },
  { id: 'office',      name: 'Ofimática',               icon: '📄' },
  { id: 'streaming',   name: 'Streaming',               icon: '📡' },
  { id: 'web',         name: 'Navegación Web',          icon: '🌐' },
  { id: 'os',          name: 'Sistema Operativo',       icon: '🪟' },
];

// ═══════════════════════════════════════════════════════════
// PROGRAMAS — añade nuevos objetos antes del cierre del array
// ═══════════════════════════════════════════════════════════
const PROGRAMS = [
  // ── VIDEO ──────────────────────────────────────────────
  { program:'CapCut', category:'video', color:'#111', shortcuts:[
    { keys:['B'],                description:'Cuchilla / Dividir clip' },
    { keys:['Ctrl','B'],         description:'Dividir en el cabezal' },
    { keys:['V'],                description:'Herramienta Selección' },
    { keys:['Ctrl','J'],         description:'Exportar Proyecto' },
    { keys:['Espacio'],          description:'Play / Pausa' },
    { keys:['I'],                description:'Marcar punto de entrada' },
    { keys:['O'],                description:'Marcar punto de salida' },
    { keys:['Ctrl','Z'],         description:'Deshacer' },
    { keys:['Ctrl','Y'],         description:'Rehacer' },
    { keys:['Delete'],           description:'Eliminar clip seleccionado' },
    { keys:['Alt','↑'],          description:'Subir nivel de pista' },
    { keys:['Alt','↓'],          description:'Bajar nivel de pista' },
    { keys:['Ctrl','R'],         description:'Velocidad del clip' },
    { keys:['Ctrl','C'],         description:'Copiar clip' },
    { keys:['Ctrl','V'],         description:'Pegar clip' },
    { keys:[','],                description:'Retroceder un frame' },
    { keys:['.'],                description:'Avanzar un frame' },
    { keys:['Ctrl','Shift','V'], description:'Pegar efectos/atributos' },
    { keys:['Alt','R'],          description:'Reemplazar clip' },
    { keys:['Ctrl','T'],         description:'Añadir Texto por defecto' },
    { keys:['M'],                description:'Añadir Marcador' },
    { keys:['Ctrl','Shift','X'], description:'Cerrar proyecto' },
    { keys:['Shift','D'],        description:'Añadir transición' },
    { keys:['Ctrl','G'],         description:'Crear clip combinado' },
  ]},
  { program:'After Effects', category:'video', color:'#00005b', shortcuts:[
    { keys:['P'],                description:'Mostrar Posición' },
    { keys:['S'],                description:'Mostrar Escala' },
    { keys:['R'],                description:'Mostrar Rotación' },
    { keys:['T'],                description:'Mostrar Opacidad' },
    { keys:['A'],                description:'Mostrar Anchor Point' },
    { keys:['U'],                description:'Ver Keyframes activos' },
    { keys:['U','U'],            description:'Ver propiedades modificadas' },
    { keys:['F9'],               description:'Easy Ease (suavizado)' },
    { keys:['Ctrl','D'],         description:'Duplicar capa' },
    { keys:['Ctrl','Shift','C'], description:'Precomponer selección' },
    { keys:['Alt','['],          description:'Recortar inicio de capa' },
    { keys:['Alt',']'],          description:'Recortar fin de capa' },
    { keys:['Ctrl','K'],         description:'Ajustes de composición' },
    { keys:['0'],                description:'Preview RAM' },
    { keys:['Ctrl','Shift','D'], description:'Dividir capa' },
    { keys:['M'],                description:'Mostrar máscara' },
    { keys:['Ctrl','Alt','F'],   description:'Ajustar al tamaño de comp' },
    { keys:['L'],                description:'Mostrar Niveles de Audio' },
    { keys:['Ctrl','Shift','Y'], description:'Nueva capa sólida' },
    { keys:['Ctrl','Alt','T'],   description:'Time Stretch' },
    { keys:['J'],                description:'Ir al Keyframe anterior' },
    { keys:['K'],                description:'Ir al siguiente Keyframe' },
    { keys:['Ctrl','Shift','H'], description:'Ocultar/Mostrar controles de capa' },
    { keys:['Shift','/'],        description:'Ajustar visor al 100%' },
    { keys:['Alt','Shift','P'],  description:'Añadir Keyframe de Posición' },
    { keys:['Alt','Shift','S'],  description:'Añadir Keyframe de Escala' },
    { keys:['Alt','Shift','R'],  description:'Añadir Keyframe de Rotación' },
    { keys:['Alt','Shift','T'],  description:'Añadir Keyframe de Opacidad' },
    { keys:['Ctrl','Alt','S'],   description:'Guardar frame actual como archivo' },
    { keys:['Ctrl','Alt','B'],   description:'Definir área de trabajo al entorno' },
    { keys:['B'],                description:'Inicio de área de trabajo' },
    { keys:['N'],                description:'Fin de área de trabajo' },
    { keys:['Ctrl','Alt','Shift','T'], description:'Ver gráfico de flujo' },
    { keys:['Ctrl','Alt','C'],   description:'Pre-componer capas' },
    { keys:['Ctrl','Shift','Alt','P'], description:'Ver visor de expresiones' },
    { keys:['J'],                description:'Ir al keyframe anterior' },
    { keys:['K'],                description:'Ir al siguiente keyframe' },
  ]},
  { program:'Premiere Pro', category:'video', color:'#1d1342', shortcuts:[
    { keys:['C'],                description:'Cuchilla (Razor)' },
    { keys:['V'],                description:'Herramienta Selección' },
    { keys:['Q'],                description:'Recorte Rizo Anterior' },
    { keys:['W'],                description:'Recorte Rizo Posterior' },
    { keys:['Ctrl','M'],         description:'Exportar Media' },
    { keys:['Shift','D'],        description:'Transición por defecto' },
    { keys:['Ctrl','K'],         description:'Corte en el cabezal' },
    { keys:['I'],                description:'Punto de entrada' },
    { keys:['O'],                description:'Punto de salida' },
    { keys:['Espacio'],          description:'Play / Pausa' },
    { keys:['Ctrl','Z'],         description:'Deshacer' },
    { keys:['Shift','1'],        description:'Ir a Ensamblaje' },
    { keys:['Shift','3'],        description:'Ir a Color' },
    { keys:['Ctrl','L'],         description:'Enlazar/desenlazar clip' },
    { keys:['G'],                description:'Velocidad/Duración del clip' },
    { keys:[','],                description:'Insertar en timeline' },
    { keys:['.'],                description:'Sobreescribir en timeline' },
    { keys:['Ctrl','Shift','E'], description:'Exportar cuadro' },
    { keys:['\\'],               description:'Zoom para ajustar toda la línea de tiempo' },
    { keys:['Shift','Delete'],   description:'Eliminar Rizo (Ripple Delete)' },
    { keys:['L'],                description:'Play (Pulsar varias veces para 2x, 4x...)' },
    { keys:['J'],                description:'Play Reversa (Pulsar varias veces para 2x...)' },
    { keys:['K'],                description:'Pausa' },
    { keys:['Shift','G'],        description:'Ganancia de Audio' },
    { keys:['Ctrl','Alt','V'],   description:'Pegar Atributos' },
    { keys:['Alt','clic'],       description:'Seleccionar solo audio o solo video' },
    { keys:['Shift','V'],        description:'Seleccionar clips hacia la derecha' },
    { keys:['Ctrl','D'],         description:'Aplicar transición de video' },
    { keys:['Ctrl','Shift','D'], description:'Aplicar transición de audio' },
    { keys:['F'],                description:'Match Frame (buscar clip original)' },
    { keys:['Ctrl','Alt','K'],   description:'Atajos de teclado' },
    { keys:['Shift','T'],        description:'Recorte fino (Trim)' },
  ]},
  { program:'DaVinci Resolve', category:'video', color:'#1a1a1a', shortcuts:[
    { keys:['A'],                description:'Herramienta Selección estándar' },
    { keys:['B'],                description:'Herramienta Cuchilla (Blade)' },
    { keys:['T'],                description:'Modo recorte dinámico (Trim)' },
    { keys:['U'],                description:'Cambiar tipo de edición (Ripple/Roll)' },
    { keys:['Espacio'],          description:'Play / Pausa' },
    { keys:['J'],                description:'Reproducir hacia atrás (pulsar varias veces para 2x...)' },
    { keys:['K'],                description:'Pausa' },
    { keys:['L'],                description:'Reproducir hacia adelante (pulsar varias veces para 2x...)' },
    { keys:['I'],                description:'Marcar punto de entrada' },
    { keys:['O'],                description:'Marcar punto de salida' },
    { keys:['Shift','Z'],        description:'Ajustar Timeline a la ventana' },
    { keys:['Ctrl','F'],         description:'Pantalla Completa' },
    { keys:['D'],                description:'Activar/desactivar clip seleccionado' },
    { keys:['Ctrl','D'],         description:'Desactivar todos los nodos (en Color)' },
    { keys:['Alt','S'],          description:'Nuevo Nodo Serial' },
    { keys:['Alt','P'],          description:'Nuevo Nodo Paralelo' },
    { keys:['Alt','L'],          description:'Nuevo Nodo de Capa (Layer)' },
    { keys:['Alt','O'],          description:'Añadir nodo fuera (Outside Node)' },
    { keys:['Ctrl','Shift','H'], description:'Activar/Desactivar Highlight (en Color)' },
    { keys:['Shift','S'],        description:'Capturar Still (en Color)' },
    { keys:['Ctrl','Alt','L'],   description:'Auto Balance de color' },
    { keys:['Shift','1-8'],      description:'Cambiar entre módulos (Media, Edit, Fusion, Color...)' },
    { keys:['Ctrl','G'],         description:'Agrupar clips' },
    { keys:['Ctrl','R'],         description:'Controles de re-tiempo (Retime)' },
    { keys:['Alt','F'],          description:'Enfocar visor (Fit)' },
    { keys:['Ctrl','M'],         description:'Añadir marcador' },
    { keys:['Shift','↑/↓'],      description:'Ir al siguiente/anterior corte' },
    { keys:['Alt','Y'],          description:'Seleccionar todos los clips a la derecha' },
    { keys:['Ctrl','Shift','['], description:'Mover clip una pista abajo' },
    { keys:['Ctrl','Shift',']'], description:'Mover clip una pista arriba' },
    { keys:['Shift','D'],        description:'Desactivar grado actual' },
    { keys:['Ctrl','Shift',','], description:'Página de Exportación (Deliver)' },
  ]},
  { program:'Sony Vegas Pro', category:'video', color:'#0070c0', shortcuts:[
    { keys:['S'],                description:'Dividir clip en la posición del cursor' },
    { keys:['M'],                description:'Insertar Marcador' },
    { keys:['G'],                description:'Agrupar clips seleccionados' },
    { keys:['U'],                description:'Desagrupar clips' },
    { keys:['V'],                description:'Mostrar/ocultar envolvente de volumen' },
    { keys:['P'],                description:'Mostrar/ocultar envolvente de paneo' },
    { keys:['Z'],                description:'Herramienta Zoom' },
    { keys:['D'],                description:'Herramienta Selección normal' },
    { keys:['Espacio'],          description:'Play / Pausa' },
    { keys:['Enter'],            description:'Play / Stop (vuelve al inicio)' },
    { keys:['Ctrl','Z'],         description:'Deshacer' },
    { keys:['Ctrl','Y'],         description:'Rehacer' },
    { keys:['Ctrl','A'],         description:'Seleccionar todo' },
    { keys:['Ctrl','Shift','A'], description:'Deseleccionar todo' },
    { keys:['Ctrl','M'],         description:'Exportar (Render As)' },
    { keys:['F4'],               description:'Propiedades del clip' },
    { keys:['Q'],                description:'Activar/desactivar Snapping' },
    { keys:['Ctrl','Shift','Q'], description:'Insertar pista de video' },
    { keys:['Ctrl','Q'],         description:'Insertar pista de audio' },
    { keys:['Alt','↑/↓'],        description:'Mover pista arriba/abajo' },
    { keys:['Shift','F5'],       description:'Snapshot de pantalla' },
    { keys:['Ctrl','Alt','↑/↓'], description:'Zoom vertical de pistas' },
    { keys:['Ctrl','Shift','W'], description:'Cerrar proyecto actual' },
    { keys:['Alt','Enter'],      description:'Propiedades del proyecto' },
    { keys:['L'],                description:'Reproducir adelante (pulsar varias veces para 2x...)' },
    { keys:['J'],                description:'Reproducir atrás (pulsar varias veces para 2x...)' },
    { keys:['K'],                description:'Pausa' },
  ]},
  { program:'Final Cut Pro', category:'video', color:'#1a1a1a', shortcuts:[
    { keys:['B'],                description:'Cuchilla (Blade)' },
    { keys:['A'],                description:'Herramienta Selección' },
    { keys:['T'],                description:'Herramienta Recorte' },
    { keys:['P'],                description:'Herramienta Posición' },
    { keys:['R'],                description:'Herramienta Rango' },
    { keys:['Cmd','B'],          description:'Dividir en el cabezal' },
    { keys:['Cmd','E'],          description:'Exportar Share Master' },
    { keys:['Espacio'],          description:'Play / Pausa' },
    { keys:['Cmd','Z'],          description:'Deshacer' },
    { keys:['I'],                description:'Punto de entrada' },
    { keys:['O'],                description:'Punto de salida' },
    { keys:['Cmd','4'],          description:'Inspector' },
    { keys:['Shift','Z'],        description:'Ajustar Timeline' },
    { keys:['W'],                description:'Insertar en primario' },
    { keys:['Q'],                description:'Conectar al primario' },
    { keys:['J'],                description:'Play reversa' },
    { keys:['K'],                description:'Pausa' },
    { keys:['L'],                description:'Play adelante' },
    { keys:['Cmd','Shift','A'],  description:'Deseleccionar todo' },
  ]},

  // ── DISEÑO ─────────────────────────────────────────────
  { program:'Photoshop', category:'graphic', color:'#001d35', shortcuts:[
    { keys:['Ctrl','J'],             description:'Duplicar capa' },
    { keys:['Ctrl','T'],             description:'Transformación libre' },
    { keys:['B'],                    description:'Pincel' },
    { keys:['E'],                    description:'Borrador' },
    { keys:['L'],                    description:'Lazo' },
    { keys:['W'],                    description:'Varita mágica / Selección rápida' },
    { keys:['Ctrl','Shift','Alt','E'],description:'Combinar en nueva capa' },
    { keys:['X'],                    description:'Intercambiar color fondo/frente' },
    { keys:['D'],                    description:'Restablecer colores negro/blanco' },
    { keys:['Ctrl','L'],             description:'Niveles' },
    { keys:['Ctrl','U'],             description:'Tono / Saturación' },
    { keys:['Ctrl','M'],             description:'Curvas' },
    { keys:['Ctrl','B'],             description:'Balance de Color' },
    { keys:['Ctrl','G'],             description:'Agrupar capas' },
    { keys:['Ctrl','Shift','I'],     description:'Invertir selección' },
    { keys:['Alt','Delete'],         description:'Rellenar con color frontal' },
    { keys:['Ctrl','Delete'],        description:'Rellenar con color de fondo' },
    { keys:['Ctrl','Alt','Z'],       description:'Paso atrás en historial' },
    { keys:['['],                    description:'Reducir tamaño de pincel' },
    { keys:[']'],                    description:'Aumentar tamaño de pincel' },
    { keys:['Ctrl','Shift','N'],     description:'Nueva capa vacía' },
    { keys: ['Ctrl','Alt','G'], description: 'Máscara de recorte' },
    { keys: ['Ctrl','Shift','Alt','N'], description: 'Nueva capa sin diálogo' },
    { keys: ['Ctrl','Alt','Shift','S'], description: 'Guardar para web' },
    { keys: ['Alt','Scroll'], description: 'Zoom suave' },
    { keys: ['Shift','Backspace'], description: 'Relleno inteligente' },
    { keys: ['Ctrl','Alt','I'], description: 'Tamaño de imagen' },
        // --- SELECCIÓN Y MOVIMIENTO ---
    { keys:['V'], description:'Mover herramienta' },
    { keys:['M'], description:'Marco rectangular / elíptico' },
    { keys:['Ctrl','D'], description:'Deseleccionar' },
    { keys:['Ctrl','Shift','D'], description:'Volver a seleccionar' },
    { keys:['Ctrl','A'], description:'Seleccionar todo' },
    { keys:['Ctrl','Shift','A'], description:'Deseleccionar todo' },
    { keys:['Ctrl','Alt','A'], description:'Seleccionar todas las capas' },
    { keys:['Shift','Click'], description:'Añadir a selección' },
    { keys:['Alt','Click'], description:'Restar de selección' },
    // --- CAPAS (MUY IMPORTANTES) ---
    { keys:['Ctrl','Shift',']'], description:'Traer capa al frente' },
    { keys:['Ctrl','Shift','['], description:'Enviar capa atrás' },
    { keys:['Ctrl',']'], description:'Subir capa un nivel' },
    { keys:['Ctrl','['], description:'Bajar capa un nivel' },
    { keys:['Ctrl','E'], description:'Combinar capas' },
    { keys:['Ctrl','Shift','E'], description:'Combinar visibles' },
    { keys:['Ctrl','Alt','Shift','E'], description:'Stamp visible (capa combinada editable)' },
    { keys:['Ctrl','Shift','G'], description:'Desagrupar capas' },
    { keys:['Ctrl','Alt','G'], description:'Crear máscara de recorte' },
    // --- HERRAMIENTAS ---
    { keys:['I'], description:'Cuentagotas' },
    { keys:['G'], description:'Bote de pintura / degradado' },
    { keys:['K'], description:'Cubo 3D / herramienta secundaria' },
    { keys:['C'], description:'Recortar (Crop)' },
    { keys:['P'], description:'Pluma (Pen tool)' },
    { keys:['T'], description:'Texto' },
    { keys:['H'], description:'Mano (Hand tool)' },
    { keys:['Z'], description:'Zoom' },
    // --- TRANSFORMACIÓN ---
    { keys:['Ctrl','Alt','T'], description:'Transformación con copia' },
    { keys:['Ctrl','Shift','T'], description:'Repetir transformación' },
    { keys:['Ctrl','0'], description:'Ajustar pantalla' },
    { keys:['Ctrl','1'], description:'Zoom 100%' },
    // --- HISTORIAL Y DESHACER ---
    { keys:['Ctrl','Z'], description:'Deshacer / rehacer (toggle)' },
    { keys:['Ctrl','Alt','Z'], description:'Paso atrás múltiple' },
    { keys:['Ctrl','Shift','Z'], description:'Paso adelante' },
    // --- SELECCIÓN AVANZADA ---
    { keys:['Ctrl','Shift','J'], description:'Cortar en nueva capa' },
    { keys:['Ctrl','Shift','Alt','R'], description:'Seleccionar y aplicar máscara' },
    // --- RELLENO Y EDICIÓN ---
    { keys:['Shift','F5'], description:'Rellenar' },
    { keys:['Shift','F6'], description:'Desvanecer selección' },
    { keys:['Alt','Backspace'], description:'Relleno según contenido (frontal)' },
    // --- GUARDADO / EXPORTACIÓN ---
    { keys:['Ctrl','S'], description:'Guardar' },
    { keys:['Ctrl','Shift','S'], description:'Guardar como' },
    { keys:['Ctrl','Alt','Shift','S'], description:'Exportar para web' },
    { keys:['Ctrl','Alt','S'], description:'Guardar copia' },
    // --- NAVEGACIÓN ---
    { keys:['Space'], description:'Mano temporal (mover lienzo)' },
    { keys:['Ctrl','+'], description:'Acercar zoom' },
    { keys:['Ctrl','-'], description:'Alejar zoom' },
    // --- MASCARAS Y AJUSTES ---
    { keys:['Ctrl','I'], description:'Invertir imagen' },
    { keys:['Ctrl','Shift','U'], description:'Desaturar' },
    { keys:['Ctrl','Alt','Shift','B'], description:'Blanco y negro automático' },
    { keys:['Q'],                    description:'Modo Máscara Rápida' },
    { keys:['Shift','F5'],           description:'Rellenar (Fill)' },
    { keys:['Ctrl','Shift','X'],     description:'Licuar (Liquify)' },
    { keys:['Ctrl','Alt','I'],       description:'Tamaño de imagen' },
    { keys:['Ctrl','Alt','C'],       description:'Tamaño de lienzo' },
    { keys:['F'],                    description:'Cambiar modo de pantalla' },
    { keys:['Tab'],                  description:'Ocultar/Mostrar paneles' },
    { keys:['Ctrl','Shift','Alt','W'],description:'Exportar como...' },
    { keys:['Ctrl','Alt','R'],       description:'Seleccionar y aplicar máscara' },
    { keys:['Ctrl','Alt','P'],       description:'Ajustes de impresión' },
    { keys:['Ctrl','K'],             description:'Preferencias generales' },
    { keys:['Shift','['],            description:'Disminuir dureza del pincel' },
    { keys:['Shift',']'],            description:'Aumentar dureza del pincel' },
  ]},
  { program:'Figma', category:'graphic', color:'#1e1e1e', shortcuts:[
    { keys:['V'],                description:'Herramienta Mover' },
    { keys:['F'],                description:'Herramienta Frame' },
    { keys:['T'],                description:'Herramienta Texto' },
    { keys:['O'],                description:'Herramienta Elipse' },
    { keys:['R'],                description:'Herramienta Rectángulo' },
    { keys:['L'],                description:'Herramienta Línea' },
    { keys:['P'],                description:'Herramienta Pluma' },
    { keys:['Shift','A'],        description:'Auto Layout' },
    { keys:['Ctrl','Alt','G'],   description:'Crear Frame' },
    { keys:['Ctrl','Shift','G'], description:'Desagrupar' },
    { keys:['Ctrl','Alt','C'],   description:'Copiar propiedades' },
    { keys:['Ctrl','Alt','V'],   description:'Pegar propiedades' },
    { keys:['Ctrl','/'],         description:'Búsqueda rápida (Quick Actions)' },
    { keys:['Ctrl','D'],         description:'Duplicar' },
    { keys:['Alt','L'],          description:'Cerrar/abrir capas' },
    { keys:['Shift','H'],        description:'Mostrar/ocultar reglas' },
    { keys:['Ctrl','Shift','3'], description:'Mostrar/ocultar contornos' },
    { keys:['Ctrl','Shift','4'], description:'Mostrar/ocultar cuadrícula' },
    { keys:['K'],                description:'Herramienta Escalar' },
    { keys:['I'],                description:'Cuentagotas (Color picker)' },
    { keys:['Ctrl','Shift','H'], description:'Esconder/mostrar UI' },
    { keys:['Ctrl','\\'],        description:'Mostrar/ocultar panel' },
    { keys:['Ctrl','Shift','K'], description:'Reemplazar imagen' },
    { keys:['Ctrl','E'],         description:'Aplanar selección' },
  ]},
  { program:'Illustrator', category:'graphic', color:'#300', shortcuts:[
    { keys:['V'],                description:'Herramienta Selección' },
    { keys:['A'],                description:'Selección Directa' },
    { keys:['P'],                description:'Herramienta Pluma' },
    { keys:['T'],                description:'Herramienta Texto' },
    { keys:['M'],                description:'Herramienta Rectángulo' },
    { keys:['L'],                description:'Herramienta Elipse' },
    { keys:['B'],                description:'Herramienta Pincel' },
    { keys:['N'],                description:'Herramienta Lápiz' },
    { keys:['R'],                description:'Herramienta Rotar' },
    { keys:['S'],                description:'Herramienta Escalar' },
    { keys:['E'],                description:'Herramienta Borrador' },
    { keys:['I'],                description:'Herramienta Cuentagotas' },
    { keys:['G'],                description:'Herramienta Degradado' },
    { keys:['W'],                description:'Herramienta Fusión (Blend)' },
    { keys:['Shift','M'],        description:'Generador de Formas (Shape Builder)' },
    { keys:['Shift','E'],        description:'Herramienta Borrador' },
    { keys:['Shift','O'],        description:'Herramienta Mesa de trabajo (Artboard)' },
    { keys:['K'],                description:'Bote de pintura dinámica' },
    { keys:['Ctrl','G'],         description:'Agrupar' },
    { keys:['Ctrl','Shift','G'], description:'Desagrupar' },
    { keys:['Ctrl','7'],         description:'Crear Máscara de Recorte' },
    { keys:['Ctrl','Alt','7'],   description:'Soltar Máscara de Recorte' },
    { keys:['Ctrl','Shift','O'], description:'Convertir texto a trazado (Outlines)' },
    { keys:['Ctrl','Shift','V'], description:'Pegar en el mismo lugar (Paste in Place)' },
    { keys:['Ctrl','Alt','Shift','V'], description:'Pegar en todas las mesas de trabajo' },
    { keys:['Ctrl','Alt','B'],   description:'Crear Fusión' },
    { keys:['Ctrl','D'],         description:'Transformar de nuevo (Duplicar acción)' },
    { keys:['Ctrl','F'],         description:'Pegar delante' },
    { keys:['Ctrl','B'],         description:'Pegar detrás' },
    { keys:['Ctrl','2'],         description:'Bloquear selección' },
    { keys:['Ctrl','Alt','2'],   description:'Desbloquear todo' },
    { keys:['Ctrl','3'],         description:'Ocultar selección' },
    { keys:['Ctrl','Alt','3'],   description:'Mostrar todo' },
    { keys:['Ctrl','Shift','['], description:'Enviar al fondo' },
    { keys:['Ctrl','Shift',']'], description:'Traer al frente' },
    { keys:['Ctrl','['],         description:'Hacia atrás' },
    { keys:['Ctrl',']'],         description:'Hacia adelante' },
    { keys:['Ctrl','Y'],         description:'Modo Contornear (Outline view)' },
    { keys:['Ctrl','Shift','Alt','Y'], description:'Previsualizar sobreimpresión' },
    { keys:['Ctrl','U'],         description:'Guías inteligentes' },
    { keys:['Ctrl','Alt',';'],   description:'Bloquear guías' },
    { keys:['Ctrl','Shift','P'], description:'Colocar imagen' },
  ]},
  { program:'InDesign', category:'graphic', color:'#49021f', shortcuts:[
    { keys:['V'],                description:'Herramienta Selección' },
    { keys:['A'],                description:'Selección Directa' },
    { keys:['T'],                description:'Herramienta Texto' },
    { keys:['P'],                description:'Herramienta Pluma' },
    { keys:['F'],                description:'Marco Rectangular' },
    { keys:['M'],                description:'Herramienta Rectángulo' },
    { keys:['L'],                description:'Herramienta Elipse' },
    { keys:['I'],                description:'Herramienta Cuentagotas' },
    { keys:['G'],                description:'Herramienta Degradado' },
    { keys:['W'],                description:'Alternar Vista Previa' },
    { keys:['Shift','W'],        description:'Modo Presentación' },
    { keys:['Ctrl','D'],         description:'Colocar (Place)' },
    { keys:['Ctrl','E'],         description:'Exportar' },
    { keys:['Ctrl','B'],         description:'Opciones de Marco de Texto' },
    { keys:['Ctrl','Alt','C'],   description:'Encajar marco al contenido' },
    { keys:['Ctrl','Alt','E'],   description:'Encajar contenido al marco' },
    { keys:['Ctrl','Shift','Alt','E'], description:'Encajar contenido proporcionalmente' },
    { keys:['Ctrl','Alt','Shift','C'], description:'Llenar marco proporcionalmente' },
    { keys:['Ctrl','G'],         description:'Agrupar' },
    { keys:['Ctrl','Shift','G'], description:'Desagrupar' },
    { keys:['Ctrl','L'],         description:'Bloquear' },
    { keys:['Ctrl','Alt','L'],   description:'Desbloquear todo' },
    { keys:['Ctrl','Alt','N'],   description:'Nueva página' },
    { keys:['Ctrl','Shift','P'], description:'Panel de Páginas' },
    { keys:['Ctrl','Alt','Shift','P'], description:'Ajustar documento' },
    { keys:['Ctrl','Alt','T'],   description:'Panel de Párrafo' },
    { keys:['Ctrl','T'],         description:'Panel de Carácter' },
    { keys:['Ctrl','F'],         description:'Buscar / Cambiar' },
    { keys:['Ctrl','Shift','D'], description:'Ver caracteres ocultos' },
    { keys:['Ctrl','Shift','Alt','B'], description:'Panel de Vínculos' },
    { keys:['Ctrl','Shift','['], description:'Enviar al fondo' },
    { keys:['Ctrl','Shift',']'], description:'Traer al frente' },
    { keys:['Shift','F7'],       description:'Panel de Alinear' },
    { keys:['F10'],              description:'Panel de Trazo' },
    { keys:['F12'],              description:'Panel de Páginas' },
  ]},
  { program:'CorelDRAW', category:'graphic', color:'#006400', shortcuts:[
    { keys:['F10'],              description:'Herramienta Forma (Shape)' },
    { keys:['F6'],               description:'Herramienta Rectángulo' },
    { keys:['F7'],               description:'Herramienta Elipse' },
    { keys:['F8'],               description:'Herramienta Texto' },
    { keys:['P'],                description:'Centrar en página' },
    { keys:['Ctrl','G'],         description:'Agrupar' },
    { keys:['Ctrl','U'],         description:'Desagrupar' },
    { keys:['Ctrl','L'],         description:'Combinar' },
    { keys:['Ctrl','K'],         description:'Separar' },
    { keys:['Ctrl','Q'],         description:'Convertir a curvas' },
    { keys:['Ctrl','I'],         description:'Importar' },
    { keys:['Ctrl','E'],         description:'Exportar' },
    { keys:['Ctrl','Shift','A'], description:'Panel de Alinear y Distribuir' },
    { keys:['Shift','F2'],       description:'Zoom sobre objetos seleccionados' },
    { keys:['F4'],               description:'Zoom sobre todos los objetos' },
    { keys:['G'],                description:'Relleno interactivo' },
    { keys:['F11'],              description:'Relleno degradado' },
    { keys:['F12'],              description:'Propiedades de contorno' },
    { keys:['Shift','F12'],      description:'Color de contorno' },
    { keys:['Ctrl','PgUp'],      description:'Hacia adelante una capa' },
    { keys:['Ctrl','PgDn'],      description:'Hacia atrás una capa' },
    { keys:['Shift','PgUp'],     description:'Al frente de la capa' },
    { keys:['Shift','PgDn'],     description:'Al fondo de la capa' },
    { keys:['Ctrl','J'],         description:'Opciones del programa' },
    { keys:['Ctrl','R'],         description:'Repetir última acción' },
  ]},
  { program:'Canva', category:'graphic', color:'#7d2ae8', shortcuts:[
    { keys:['T'],                description:'Añadir texto' },
    { keys:['R'],                description:'Añadir rectángulo' },
    { keys:['C'],                description:'Añadir círculo' },
    { keys:['Ctrl','D'],         description:'Duplicar elemento' },
    { keys:['Ctrl','G'],         description:'Agrupar elementos' },
    { keys:['Ctrl','Shift','G'], description:'Desagrupar elementos' },
    { keys:['Ctrl','Z'],         description:'Deshacer' },
    { keys:['Ctrl','Shift','Z'], description:'Rehacer' },
    { keys:['Delete'],           description:'Eliminar elemento' },
    { keys:['Ctrl','A'],         description:'Seleccionar todo' },
    { keys:['Alt','N'],          description:'Nueva página' },
    { keys:['Ctrl','F'],         description:'Buscar elemento' },
    { keys:['Ctrl','→'],         description:'Enviar al frente' },
    { keys:['Ctrl','←'],         description:'Enviar al fondo' },
  ]},

  // ── AUDIO ──────────────────────────────────────────────
  { program:'FL Studio', category:'audio', color:'#1a0a00', shortcuts:[
    { keys:['F9'],               description:'Abrir Mezclador (Mixer)' },
    { keys:['F7'],               description:'Abrir Piano Roll' },
    { keys:['F5'],               description:'Abrir Playlist' },
    { keys:['F6'],               description:'Abrir Step Sequencer' },
    { keys:['Ctrl','L'],         description:'Asignar canal al Mixer' },
    { keys:['Espacio'],          description:'Play / Pausa' },
    { keys:['Enter'],            description:'Reproducir desde inicio' },
    { keys:['Ctrl','Z'],         description:'Deshacer' },
    { keys:['Ctrl','S'],         description:'Guardar proyecto' },
    { keys:['Ctrl','R'],         description:'Exportar como WAV' },
    { keys:['Ctrl','Shift','S'], description:'Guardar nueva versión' },
    { keys:['Ctrl','P'],         description:'Piano Roll del canal actual' },
    { keys:['Ctrl','M'],         description:'Abrir MIDI Settings' },
    { keys:['Alt','G'],          description:'Abrir generador seleccionado' },
    { keys:['B'],                description:'Herramienta Pintar' },
    { keys:['C'],                description:'Herramienta Cuchilla' },
    { keys:['P'],                description:'Herramienta Dibujar' },
    { keys:['S'],                description:'Herramienta Slip' },
    { keys:['Shift','Q'],        description:'Cuantizar rápido' },
    { keys:['Ctrl','Q'],         description:'Cuantización detallada' },
    { keys:['Alt','A'],          description:'Herramienta Arpegiador (Piano Roll)' },
    { keys:['Alt','S'],          description:'Herramienta Strum (Piano Roll)' },
    { keys:['Ctrl','Roll'],      description:'Zoom horizontal' },
    { keys:['Ctrl','Alt','Roll'],       description:'Zoom vertical' },
  ]},
  { program:'Audacity', category:'audio', color:'#00003c', shortcuts:[
    { keys:['Espacio'],          description:'Reproducir / Pausa' },
    { keys:['R'],                description:'Grabar' },
    { keys:['Shift','R'],        description:'Grabar en pista nueva' },
    { keys:['Ctrl','Shift','I'], description:'Importar audio' },
    { keys:['Ctrl','Shift','E'], description:'Exportar audio' },
    { keys:['Ctrl','I'],         description:'Dividir clip' },
    { keys:['Ctrl','J'],         description:'Unir clips' },
    { keys:['Ctrl','L'],         description:'Silenciar selección' },
    { keys:['Ctrl','T'],         description:'Recortar audio fuera de selección' },
    { keys:['Z'],                description:'Encontrar cruces por cero' },
    { keys:['F1'],               description:'Herramienta Selección' },
    { keys:['F2'],               description:'Herramienta Envolvente' },
    { keys:['Ctrl','Shift','N'], description:'Nueva pista' },
    { keys:['Ctrl','A'],         description:'Seleccionar todo' },
    { keys:['Ctrl','D'],         description:'Duplicar selección' },
    { keys:['Ctrl','K'],         description:'Eliminar selección' },
    { keys:['Ctrl','Shift','E'], description:'Exportar múltiples archivos' },
    { keys:['Ctrl','B'],         description:'Añadir etiqueta en cursor' },
  ]},
  { program:'Adobe Audition', category:'audio', color:'#00005b', shortcuts:[
    { keys:['Espacio'],          description:'Play / Pausa' },
    { keys:['Shift','Espacio'],  description:'Reproducir desde el inicio' },
    { keys:['Ctrl','K'],         description:'Dividir clip' },
    { keys:['Shift','D'],        description:'Duplicar clip' },
    { keys:['Ctrl','Shift','K'], description:'Ripple Delete' },
    { keys:['G'],                description:'Agrupar clips' },
    { keys:['R'],                description:'Grabar' },
    { keys:['Ctrl','E'],         description:'Exportar archivo de audio' },
    { keys:['Ctrl','Shift','E'], description:'Exportar Multi-Track Mix' },
    { keys:['M'],                description:'Insertar marcador' },
    { keys:['Ctrl','Z'],         description:'Deshacer' },
    { keys:['Ctrl','Shift','M'], description:'Silenciar pista' },
    { keys:['F'],                description:'Zoom a selección' },
    { keys:['Ctrl','L'],         description:'Normalizar' },
  ]},
  { program:'Ableton Live', category:'audio', color:'#222', shortcuts:[
    { keys:['Tab'],              description:'Alternar Vista Session / Arrangement' },
    { keys:['Ctrl','D'],         description:'Duplicar clip / selección' },
    { keys:['Ctrl','E'],         description:'Dividir clip (Split)' },
    { keys:['Ctrl','J'],         description:'Consolidar clips (Join)' },
    { keys:['Espacio'],          description:'Reproducir / Pausa' },
    { keys:['Shift','Espacio'],  description:'Continuar reproducción' },
    { keys:['Ctrl','T'],         description:'Insertar pista de Audio' },
    { keys:['Ctrl','Shift','T'], description:'Insertar pista MIDI' },
    { keys:['Ctrl','Alt','T'],   description:'Insertar pista de Retorno' },
    { keys:['Ctrl','G'],         description:'Agrupar pistas' },
    { keys:['Ctrl','Shift','G'], description:'Desagrupar pistas' },
    { keys:['Ctrl','Alt','B'],   description:'Mostrar/ocultar Navegador (Browser)' },
    { keys:['Ctrl','Alt','L'],   description:'Mostrar/ocultar Detalle (Clip/Device)' },
    { keys:['Shift','Tab'],      description:'Cambiar entre Clip y Device' },
    { keys:['Ctrl','M'],         description:'Activar mapeo MIDI' },
    { keys:['Ctrl','K'],         description:'Activar mapeo de Teclas' },
    { keys:['Ctrl','L'],         description:'Seleccionar Loop' },
    { keys:['Ctrl','Shift','F'], description:'Seguir reproducción (Follow)' },
    { keys:['Ctrl','Shift','L'], description:'Activar/desactivar Loop' },
    { keys:['F9'],               description:'Grabar' },
    { keys:['+','-'],            description:'Zoom In / Out' },
    { keys:['Ctrl','R'],         description:'Exportar Audio (Render)' },
    { keys:['Ctrl','U'],         description:'Cuantizar selección' },
  ]},
  { program:'Logic Pro', category:'audio', color:'#1a1a1a', shortcuts:[
    { keys:['Espacio'],          description:'Play / Pausa' },
    { keys:['Enter'],            description:'Ir al inicio' },
    { keys:['R'],                description:'Grabar' },
    { keys:['Cmd','T'],          description:'Dividir regiones en el cabezal' },
    { keys:['Cmd','J'],          description:'Unir regiones' },
    { keys:['Cmd','D'],          description:'Duplicar región' },
    { keys:['Cmd','A'],          description:'Seleccionar todo' },
    { keys:['L'],                description:'Activar bucle (Loop) de región' },
    { keys:['S'],                description:'Solo pista' },
    { keys:['M'],                description:'Silenciar pista' },
    { keys:['X'],                description:'Mostrar/ocultar Mezclador' },
    { keys:['E'],                description:'Mostrar/ocultar Editores' },
    { keys:['I'],                description:'Mostrar/ocultar Inspector' },
    { keys:['B'],                description:'Mostrar/ocultar Smart Controls' },
    { keys:['Y'],                description:'Mostrar/ocultar Librería' },
    { keys:['G'],                description:'Mostrar/ocultar Pistas Globales' },
    { keys:['Cmd','K'],          description:'Teclado Musical en pantalla' },
    { keys:['Cmd','U'],          description:'Cuantizar notas MIDI' },
    { keys:['Cmd','R'],          description:'Exportar (Bounce)' },
    { keys:['Cmd','Shift','N'],  description:'Nueva pista' },
    { keys:['V'],                description:'Ocultar/mostrar todos los plugins' },
    { keys:['T'],                description:'Abrir menú de Herramientas' },
  ]},

  // ── 3D ─────────────────────────────────────────────────
  { program:'Blender', category:'3d', color:'#1a0e00', shortcuts:[
    { keys:['G'],                description:'Mover (Grab)' },
    { keys:['S'],                description:'Escalar' },
    { keys:['R'],                description:'Rotar' },
    { keys:['E'],                description:'Extruir' },
    { keys:['I'],                description:'Insertar cara (Inset)' },
    { keys:['K'],                description:'Cuchillo (Knife)' },
    { keys:['Tab'],              description:'Cambiar entre Modo Objeto / Edición' },
    { keys:['Z'],                description:'Menú de Shading (Wireframe, Render...)' },
    { keys:['Ctrl','B'],         description:'Biselar (Bevel)' },
    { keys:['Ctrl','R'],         description:'Corte en bucle (Loop Cut)' },
    { keys:['Alt','S'],          description:'Escalar a lo largo de normales' },
    { keys:['H'],                description:'Ocultar selección' },
    { keys:['Alt','H'],          description:'Mostrar todo lo oculto' },
    { keys:['Shift','A'],        description:'Añadir objeto' },
    { keys:['Shift','D'],        description:'Duplicar objeto' },
    { keys:['M'],                description:'Mover a colección' },
    { keys:['X'],                description:'Eliminar' },
    { keys:['F2'],               description:'Cambiar nombre' },
    { keys:['Num7'],             description:'Vista Superior' },
    { keys:['Num1'],             description:'Vista Frontal' },
    { keys:['Num3'],             description:'Vista Lateral Derecha' },
    { keys:['Num9'],             description:'Vista Opuesta' },
    { keys:['Num5'],             description:'Alternar Perspectiva / Ortogonal' },
    { keys:['Num0'],             description:'Vista de Cámara' },
    { keys:['Ctrl','Alt','Num0'],description:'Alinear cámara a la vista actual' },
    { keys:['F12'],              description:'Renderizar imagen' },
    { keys:['Ctrl','F12'],       description:'Renderizar animación' },
    { keys:['Shift','Z'],        description:'Alternar modo Render en el visor' },
    { keys:['.'],                description:'Enfocar objeto seleccionado' },
  ]},
  { program:'Maya', category:'3d', color:'#0b1f22', shortcuts:[
    { keys:['Q'],                description:'Selección' },
    { keys:['W'],                description:'Mover' },
    { keys:['E'],                description:'Rotar' },
    { keys:['R'],                description:'Escalar' },
    { keys:['F'],                description:'Enfocar selección' },
    { keys:['G'],                description:'Repetir última acción' },
    { keys:['B'],                description:'Selección suave (Soft Selection)' },
    { keys:['1'],                description:'Modo subdivisión baja' },
    { keys:['3'],                description:'Modo suavizado (Smooth)' },
    { keys:['4'],                description:'Vista de alambre (Wireframe)' },
    { keys:['5'],                description:'Vista sombreada (Shaded)' },
    { keys:['6'],                description:'Vista con texturas' },
    { keys:['7'],                description:'Vista con luces' },
    { keys:['Ctrl','D'],         description:'Duplicar' },
    { keys:['Shift','D'],        description:'Duplicar con transformación' },
    { keys:['Ctrl','G'],         description:'Agrupar' },
    { keys:['P'],                description:'Emparentar (Parent)' },
    { keys:['Shift','P'],        description:'Desemparentar' },
    { keys:['Alt','Clic'],       description:'Orbitar' },
    { keys:['Alt','Clic-Medio'], description:'Paneo' },
    { keys:['Alt','Clic-Der'],   description:'Zoom' },
    { keys:['Espacio'],          description:'Cambiar entre vistas (Hold para menú)' },
  ]},
  { program:'Cinema 4D', category:'3d', color:'#001a3a', shortcuts:[
    { keys:['E'],                description:'Mover' },
    { keys:['R'],                description:'Rotar' },
    { keys:['T'],                description:'Escalar' },
    { keys:['C'],                description:'Hacer editable' },
    { keys:['F1'],               description:'Vista Perspectiva' },
    { keys:['F2'],               description:'Vista Superior' },
    { keys:['F3'],               description:'Vista Lateral' },
    { keys:['F4'],               description:'Vista Frontal' },
    { keys:['F5'],               description:'Ver todas las vistas' },
    { keys:['Ctrl','R'],         description:'Renderizar visor' },
    { keys:['Shift','R'],        description:'Renderizar a Picture Viewer' },
    { keys:['Ctrl','B'],         description:'Configuración de Render' },
    { keys:['U','L'],            description:'Selección cíclica (Loop Selection)' },
    { keys:['U','O'],            description:'Optimizar' },
    { keys:['M','S'],            description:'Biselar (Bevel)' },
    { keys:['M','K'],            description:'Corte de cuchillo' },
    { keys:['D'],                description:'Extruir' },
    { keys:['I'],                description:'Extrusión interior' },
    { keys:['Ctrl','Z'],         description:'Deshacer' },
    { keys:['V'],                description:'Menú de comandos rápidos' },
  ]},
  { program:'ZBrush', category:'3d', color:'#2a2a2a', shortcuts:[
    { keys:['X'],                description:'Activar Simetría' },
    { keys:['S'],                description:'Tamaño del pincel' },
    { keys:['I'],                description:'Intensidad Focal' },
    { keys:['O'],                description:'Intensidad Z' },
    { keys:['Q'],                description:'Modo Dibujar (Draw)' },
    { keys:['W'],                description:'Modo Mover (Gizmo)' },
    { keys:['E'],                description:'Modo Escalar' },
    { keys:['R'],                description:'Modo Rotar' },
    { keys:['Ctrl','D'],         description:'Dividir geometría' },
    { keys:['Shift','D'],        description:'Bajar nivel de subdivisión' },
    { keys:['D'],                description:'Subir nivel de subdivisión' },
    { keys:['Shift','F'],        description:'Ver malla (Polyframe)' },
    { keys:['F'],                description:'Enfocar modelo' },
    { keys:['Alt','Clic'],       description:'Navegar (Orbitar)' },
    { keys:['Ctrl','Shift','Clic'], description:'Selección de visibilidad' },
    { keys:['Ctrl','Clic'],      description:'Enmascarar' },
    { keys:['B'],                description:'Librería de pinceles' },
  ]},
  { program:'SketchUp', category:'3d', color:'#b22222', shortcuts:[
    { keys:['Espacio'],          description:'Selección' },
    { keys:['L'],                description:'Línea' },
    { keys:['P'],                description:'Empujar/Tirar (Push/Pull)' },
    { keys:['R'],                description:'Rectángulo' },
    { keys:['C'],                description:'Círculo' },
    { keys:['A'],                description:'Arco' },
    { keys:['M'],                description:'Mover' },
    { keys:['Q'],                description:'Rotar' },
    { keys:['S'],                description:'Escalar' },
    { keys:['F'],                description:'Equidistancia (Offset)' },
    { keys:['E'],                description:'Borrar' },
    { keys:['T'],                description:'Cinta métrica' },
    { keys:['B'],                description:'Bote de pintura' },
    { keys:['G'],                description:'Crear Componente' },
    { keys:['Z'],                description:'Zoom' },
    { keys:['O'],                description:'Orbitar' },
    { keys:['H'],                description:'Desplazar (Pan)' },
  ]},
  { program:'Unity', category:'3d', color:'#222', shortcuts:[
    { keys:['Q'],                description:'Herramienta Mano (Pan)' },
    { keys:['W'],                description:'Herramienta Mover' },
    { keys:['E'],                description:'Herramienta Rotar' },
    { keys:['R'],                description:'Herramienta Escalar' },
    { keys:['T'],                description:'Herramienta Rect' },
    { keys:['Y'],                description:'Herramienta Transformación Pro' },
    { keys:['Z'],                description:'Cambiar Pivot (Center/Pivot)' },
    { keys:['X'],                description:'Cambiar Coordenadas (Global/Local)' },
    { keys:['F'],                description:'Enfocar objeto seleccionado' },
    { keys:['Ctrl','P'],         description:'Play / Pausa' },
    { keys:['Ctrl','Shift','P'], description:'Paso a paso' },
    { keys:['Ctrl','D'],         description:'Duplicar objeto' },
    { keys:['Ctrl','Shift','N'], description:'Crear objeto vacío' },
    { keys:['Ctrl','1'],         description:'Ventana de Escena' },
    { keys:['Ctrl','2'],         description:'Ventana de Juego' },
    { keys:['Ctrl','3'],         description:'Ventana de Inspector' },
    { keys:['Ctrl','4'],         description:'Ventana de Jerarquía' },
    { keys:['Ctrl','5'],         description:'Ventana de Proyecto' },
    { keys:['Ctrl','6'],         description:'Ventana de Animación' },
    { keys:['Ctrl','9'],         description:'Ventana de Asset Store' },
    { keys:['Ctrl','0'],         description:'Ventana de Servicios' },
    { keys:['V'],                description:'Vértice Snap' },
  ]},
  { program:'Unreal Engine', category:'3d', color:'#000', shortcuts:[
    { keys:['W'],                description:'Mover' },
    { keys:['E'],                description:'Rotar' },
    { keys:['R'],                description:'Escalar' },
    { keys:['F'],                description:'Enfocar' },
    { keys:['G'],                description:'Modo Juego (ocultar iconos)' },
    { keys:['H'],                description:'Ocultar seleccionado' },
    { keys:['Ctrl','H'],         description:'Mostrar todo' },
    { keys:['Alt','S'],          description:'Simular' },
    { keys:['Alt','P'],          description:'Jugar (Play)' },
    { keys:['Esc'],              description:'Detener Simulación/Juego' },
    { keys:['Ctrl','B'],         description:'Buscar en el Navegador de Contenido' },
    { keys:['Ctrl','Space'],     description:'Abrir Cajón de Contenido (Drawer)' },
    { keys:['End'],              description:'Alinear objeto al suelo' },
    { keys:['Alt','V'],          description:'Modo de vista: Wireframe' },
    { keys:['Alt','4'],          description:'Modo de vista: Lit' },
    { keys:['Alt','3'],          description:'Modo de vista: Unlit' },
    { keys:['Ctrl','Z'],         description:'Deshacer' },
    { keys:['Ctrl','Y'],         description:'Rehacer' },
    { keys:['Ctrl','D'],         description:'Duplicar' },
    { keys:['F11'],              description:'Pantalla completa' },
  ]},

  // ── INGENIERÍA ──────────────────────────────────────────
  { program:'AutoCAD', category:'engineering', color:'#cc0000', shortcuts:[
    { keys:['L','Enter'],        description:'Línea (Line)' },
    { keys:['PL','Enter'],       description:'Polilínea' },
    { keys:['REC','Enter'],      description:'Rectángulo' },
    { keys:['C','Enter'],        description:'Círculo' },
    { keys:['TR','Enter'],       description:'Recortar (Trim)' },
    { keys:['EX','Enter'],       description:'Extender (Extend)' },
    { keys:['O','Enter'],        description:'Desfase (Offset)' },
    { keys:['M','Enter'],        description:'Mover' },
    { keys:['CO','Enter'],       description:'Copiar' },
    { keys:['RO','Enter'],       description:'Rotar' },
    { keys:['SC','Enter'],       description:'Escalar' },
    { keys:['MI','Enter'],       description:'Simetría (Mirror)' },
    { keys:['F','Enter'],        description:'Empalme (Fillet)' },
    { keys:['H','Enter'],        description:'Sombreado (Hatch)' },
    { keys:['X','Enter'],        description:'Descomponer (Explode)' },
    { keys:['B','Enter'],        description:'Crear Bloque' },
    { keys:['I','Enter'],        description:'Insertar Bloque' },
    { keys:['LA','Enter'],       description:'Administrador de Capas' },
    { keys:['MA','Enter'],       description:'Igualar Propiedades' },
    { keys:['DI','Enter'],       description:'Distancia' },
    { keys:['F3'],               description:'Alternar OSNAP (Snap)' },
    { keys:['F8'],               description:'Modo Orto' },
    { keys:['F10'],              description:'Seguimiento Polar' },
    { keys:['Ctrl','1'],         description:'Paleta de Propiedades' },
    { keys:['Ctrl','9'],         description:'Línea de comandos On/Off' },
    { keys:['Z','Enter','E','Enter'], description:'Zoom Extensión' },
  ]},
  { program:'SolidWorks', category:'engineering', color:'#C0392B', shortcuts:[
    { keys:['S'],                description:'Menú de atajos rápidos' },
    { keys:['D'],                description:'Confirmar selección / OK' },
    { keys:['L'],                description:'Línea' },
    { keys:['C'],                description:'Círculo' },
    { keys:['R'],                description:'Rectángulo' },
    { keys:['Ctrl','B'],         description:'Reconstruir' },
    { keys:['Ctrl','Q'],         description:'Reconstrucción forzada' },
    { keys:['F'],                description:'Zoom para ajustar' },
    { keys:['G'],                description:'Lupa' },
    { keys:['Espacio'],          description:'Selector de Vistas' },
    { keys:['Ctrl','1'],         description:'Vista Frontal' },
    { keys:['Ctrl','2'],         description:'Vista Trasera' },
    { keys:['Ctrl','3'],         description:'Vista Izquierda' },
    { keys:['Ctrl','4'],         description:'Vista Derecha' },
    { keys:['Ctrl','5'],         description:'Vista Superior' },
    { keys:['Ctrl','6'],         description:'Vista Inferior' },
    { keys:['Ctrl','7'],         description:'Vista Isométrica' },
    { keys:['Ctrl','8'],         description:'Normal a la selección' },
    { keys:['Alt','Clic'],       description:'Girar cámara' },
    { keys:['Ctrl','Z'],         description:'Deshacer' },
    { keys:['Shift','C'],        description:'Colapsar árbol de diseño' },
  ]},
  { program:'Revit', category:'engineering', color:'#2B5796', shortcuts:[
    { keys:['W','A'],            description:'Muro (Wall)' },
    { keys:['D','R'],            description:'Puerta (Door)' },
    { keys:['W','N'],            description:'Ventana (Window)' },
    { keys:['C','M'],            description:'Componente' },
    { keys:['L','I'],            description:'Línea de detalle' },
    { keys:['D','I'],            description:'Cota Alineada' },
    { keys:['T','X'],            description:'Texto' },
    { keys:['G','R'],            description:'Rejilla (Grid)' },
    { keys:['A','L'],            description:'Alinear' },
    { keys:['O','F'],            description:'Desfase (Offset)' },
    { keys:['M','M'],            description:'Reflejar (Mirror) - seleccionar eje' },
    { keys:['D','M'],            description:'Reflejar (Mirror) - dibujar eje' },
    { keys:['S','L'],            description:'Dividir elemento' },
    { keys:['T','R'],            description:'Recortar/Extender (Trim)' },
    { keys:['M','V'],            description:'Mover' },
    { keys:['C','O'],            description:'Copiar' },
    { keys:['R','O'],            description:'Rotar' },
    { keys:['V','G'],            description:'Visibilidad / Gráficos' },
    { keys:['H','H'],            description:'Ocultar temporalmente' },
    { keys:['H','R'],            description:'Restablecer aislar/ocultar' },
    { keys:['E','H'],            description:'Ocultar en vista' },
    { keys:['W','T'],            description:'Mosaico de ventanas' },
    { keys:['Z','A'],            description:'Zoom todo' },
  ]},
  { program:'Matlab', category:'engineering', color:'#003f6b', shortcuts:[
    { keys:['Ctrl','Enter'],     description:'Ejecutar sección actual' },
    { keys:['F5'],               description:'Ejecutar todo el script' },
    { keys:['Ctrl','C'],         description:'Interrumpir ejecución' },
    { keys:['Tab'],              description:'Autocompletar' },
    { keys:['↑'],                description:'Comando anterior (historial)' },
    { keys:['Ctrl','R'],         description:'Comentar selección' },
    { keys:['Ctrl','T'],         description:'Descomentar selección' },
    { keys:['Ctrl','N'],         description:'Nuevo script' },
    { keys:['F10'],              description:'Step Over (depuración)' },
    { keys:['F11'],              description:'Step In (depuración)' },
    { keys:['Ctrl','D'],         description:'Ver documentación función' },
  ]},
  { program:'CATIA', category:'engineering', color:'#003087', shortcuts:[
    { keys:['F3'],               description:'Ocultar/mostrar árbol de entidades' },
    { keys:['H'],                description:'Ocultar/mostrar objeto' },
    { keys:['V'],                description:'Ver sólo seleccionado' },
    { keys:['Ctrl','U'],         description:'Actualizar cuerpo activo' },
    { keys:['Ctrl','Z'],         description:'Deshacer' },
    { keys:['Ctrl','W'],         description:'Ventana nueva' },
    { keys:['Escape'],           description:'Cancelar comando activo' },
    { keys:['Alt','clic'],       description:'Seleccionar oculto' },
    { keys:['Ctrl','PageUp'],    description:'Vista siguiente' },
    { keys:['Ctrl','PageDown'],  description:'Vista anterior' },
  ]},

  // ── MEDICINA ─────────────────────────────────────────────
  { program:'Anki', category:'medicine', shortcuts:[
    { keys:['Espacio'],          description:'Mostrar respuesta / Aprobar' },
    { keys:['1'],                description:'Otra vez (vuelve pronto)' },
    { keys:['2'],                description:'Difícil' },
    { keys:['3'],                description:'Bien' },
    { keys:['4'],                description:'Fácil' },
    { keys:['A'],                description:'Añadir tarjeta nueva' },
    { keys:['E'],                description:'Editar tarjeta actual' },
    { keys:['*'],                description:'Marcar tarjeta' },
    { keys:['Delete'],           description:'Eliminar tarjeta' },
    { keys:['Ctrl','Z'],         description:'Deshacer última acción' },
    { keys:['@'],                description:'Suspender tarjeta' },
    { keys:['!'],                description:'Marcar como fallida' },
    { keys:['Ctrl','F'],         description:'Buscar en el mazo' },
  ]},
  { program:'OsiriX / Horos', category:'medicine', shortcuts:[
    { keys:['M'],                description:'Herramienta Medición' },
    { keys:['Ctrl','L'],         description:'Ajuste de Ventana (W/L)' },
    { keys:['Ctrl','3'],         description:'Reconstrucción 3D' },
    { keys:['←','→'],            description:'Navegar entre series' },
    { keys:['↑','↓'],            description:'Navegar entre cortes' },
    { keys:['R'],                description:'Herramienta ROI' },
    { keys:['Shift','clic'],     description:'Añadir punto a ROI' },
    { keys:['Escape'],           description:'Deseleccionar herramienta' },
    { keys:['Ctrl','E'],         description:'Exportar imágenes' },
    { keys:['Cmd','I'],          description:'Info del paciente' },
  ]},
  { program:'Complete Anatomy', category:'medicine', shortcuts:[
    { keys:['R'],                description:'Rotar modelo 3D' },
    { keys:['F'],                description:'Buscar estructura anatómica' },
    { keys:['Espacio'],          description:'Ocultar/mostrar capas' },
    { keys:['+'],                description:'Añadir estructura a selección' },
    { keys:['-'],                description:'Quitar estructura de selección' },
    { keys:['Ctrl','Z'],         description:'Deshacer disección' },
    { keys:['A'],                description:'Vista anterior' },
    { keys:['P'],                description:'Vista posterior' },
    { keys:['S'],                description:'Vista superior' },
    { keys:['L'],                description:'Cambiar vista lateral' },
  ]},
  { program:'PubMed', category:'medicine', shortcuts:[
    { keys:['[tiab]'],           description:'Buscar en Título y Resumen' },
    { keys:['[MeSH]'],           description:'Buscar término MeSH exacto' },
    { keys:['[au]'],             description:'Filtrar por autor' },
    { keys:['[dp]'],             description:'Filtrar por fecha de publicación' },
    { keys:['[jour]'],           description:'Filtrar por revista' },
    { keys:['[pt]'],             description:'Filtrar por tipo de publicación' },
    { keys:['AND'],              description:'Operador booleano AND' },
    { keys:['OR'],               description:'Operador booleano OR' },
    { keys:['NOT'],              description:'Operador booleano NOT' },
    { keys:['"..."'],            description:'Búsqueda de frase exacta' },
    { keys:['*'],                description:'Truncamiento de término' },
  ]},

  // ── DEV / IT ─────────────────────────────────────────────
  { program:'VS Code', category:'dev', color:'#007ACC', shortcuts:[
    { keys:['Ctrl','P'],         description:'Ir a archivo (Go to File)' },
    { keys:['Ctrl','Shift','P'], description:'Paleta de comandos' },
    { keys:['Ctrl','`'],         description:'Abrir Terminal integrado' },
    { keys:['Ctrl','Shift','`'], description:'Nueva terminal' },
    { keys:['Alt','Shift','F'],  description:'Formatear documento' },
    { keys:['F2'],               description:'Renombrar símbolo' },
    { keys:['Ctrl','/'],         description:'Comentar/Descomentar línea' },
    { keys:['Ctrl','D'],         description:'Seleccionar siguiente ocurrencia' },
    { keys:['Ctrl','Shift','L'], description:'Seleccionar todas las ocurrencias' },
    { keys:['Alt','↑/↓'],        description:'Mover línea arriba/abajo' },
    { keys:['Ctrl','Shift','K'], description:'Eliminar línea' },
    { keys:['F12'],              description:'Ir a definición' },
    { keys:['Ctrl','B'],         description:'Mostrar/ocultar Sidebar' },
    { keys:['Ctrl','G'],         description:'Ir a línea' },
    { keys:['Ctrl','H'],         description:'Buscar y reemplazar' },
    { keys:['Ctrl','Shift','F'], description:'Buscar en todos los archivos' },
    { keys:['Ctrl','\\'],        description:'Dividir editor' },
    { keys:['Alt','Shift','↑'],  description:'Copiar línea arriba' },
    { keys:['Ctrl','K','Ctrl','S'],description:'Ver atajos de teclado' },
    { keys:['Ctrl','Shift','E'], description:'Ver Explorador de archivos' },
    { keys:['Ctrl','Shift','G'], description:'Ver Control de Código Fuente' },
    { keys:['Ctrl','Shift','X'], description:'Ver Extensiones' },
    { keys:['Ctrl','Shift','D'], description:'Ver Depuración' },
    { keys:['Ctrl','W'],         description:'Cerrar editor actual' },
    { keys:['Ctrl','Shift','W'], description:'Cerrar ventana' },
    { keys:['Ctrl','Shift','T'], description:'Reabrir último editor cerrado' },
    { keys:['Ctrl','Tab'],       description:'Siguiente editor abierto' },
    { keys:['Ctrl','K','V'],     description:'Abrir previsualización Markdown' },
    { keys:['Ctrl','K','Enter'], description:'Mantener editor abierto' },
    { keys:['Ctrl','Alt','N'],   description:'Nueva ventana' },
    { keys:['Ctrl','Shift','['], description:'Plegar código' },
    { keys:['Ctrl','Shift',']'], description:'Desplegar código' },
    { keys:['Ctrl','K','0'],     description:'Plegar todos los niveles' },
    { keys:['Ctrl','K','J'],     description:'Desplegar todos los niveles' },
    { keys:['Ctrl','Shift','U'], description:'Mostrar panel de Salida' },
    { keys:['Ctrl','Shift','M'], description:'Mostrar panel de Problemas' },
    { keys:['Ctrl','K','Ctrl','I'],description:'Mostrar información al pasar el ratón (Hover)' },
    { keys:['Alt','Z'],          description:'Alternar ajuste de línea (Word Wrap)' },
    { keys:['Ctrl','K','Z'],     description:'Modo Zen' },
    { keys:['Ctrl','Shift','V'], description:'Previsualizar Markdown' },
    { keys:['Ctrl','K','M'],     description:'Cambiar lenguaje del archivo' },
    { keys:['Ctrl','Shift','.'], description:'Navegar por símbolos (Breadcrumbs)' },
    { keys:['Ctrl','Shift','Alt','N'],description:'Nueva ventana' },
    { keys:['Ctrl','.'],         description:'Quick Fix / Acciones rápidas' },
    { keys:['Alt','Shift','A'],  description:'Comentar bloque de código' },
    { keys:['Ctrl','K','Ctrl','X'],description:'Eliminar espacios al final' },
    { keys:['Ctrl','Alt','↑/↓'], description:'Insertar cursor arriba/abajo' },
    { keys:['Ctrl','Shift','Alt','→'],description:'Expandir selección' },
    { keys:['Ctrl','Shift','Alt','←'],description:'Contraer selección' },
    { keys:['Ctrl','K','Ctrl','D'],description:'Mover archivo al final' },
    { keys:['F8'],               description:'Ir al siguiente error' },
    { keys:['Shift','F8'],       description:'Ir al error anterior' },
    { keys:['Ctrl','K','C'],     description:'Comentar bloque' },
    { keys:['Ctrl','K','U'],     description:'Descomentar bloque' },
  ]},
  { program:'Docker', category:'dev', color:'#2496ed', shortcuts:[
    { keys:['docker','ps'],      description:'Listar contenedores activos' },
    { keys:['docker','ps','-a'], description:'Listar todos los contenedores' },
    { keys:['docker','images'],  description:'Listar imágenes locales' },
    { keys:['docker','run'],     description:'Crear y arrancar contenedor' },
    { keys:['docker','exec','-it'], description:'Entrar a terminal de contenedor' },
    { keys:['docker','stop'],    description:'Detener contenedor' },
    { keys:['docker','start'],   description:'Arrancar contenedor detenido' },
    { keys:['docker','rm'],      description:'Eliminar contenedor' },
    { keys:['docker','rmi'],     description:'Eliminar imagen' },
    { keys:['docker','logs','-f'], description:'Ver logs en tiempo real' },
    { keys:['docker-compose','up'],description:'Levantar servicios stack' },
    { keys:['docker-compose','down'],description:'Detener y eliminar servicios' },
    { keys:['docker','system','prune'],description:'Limpiar recursos no usados' },
  ]},
  { program:'Git', category:'dev', color:'#f05032', shortcuts:[
    { keys:['git','status'],     description:'Ver estado del repositorio' },
    { keys:['git','add','.'],    description:'Preparar todos los cambios' },
    { keys:['git','commit','-m'],description:'Confirmar cambios con mensaje' },
    { keys:['git','push'],       description:'Subir cambios al remoto' },
    { keys:['git','pull'],       description:'Bajar cambios del remoto' },
    { keys:['git','fetch'],      description:'Descargar info del remoto' },
    { keys:['git','checkout','-b'],description:'Crear y cambiar a nueva rama' },
    { keys:['git','branch'],     description:'Listar ramas' },
    { keys:['git','merge'],      description:'Fusionar rama' },
    { keys:['git','log','--oneline'],description:'Ver historial simplificado' },
    { keys:['git','stash'],      description:'Guardar cambios temporalmente' },
    { keys:['git','stash','pop'],description:'Recuperar cambios guardados' },
    { keys:['git','reset','--hard'],description:'Deshacer todo (¡Cuidado!)' },
    { keys:['git','diff'],       description:'Ver diferencias' },
    { keys:['git','remote','-v'],description:'Ver URLs remotas' },
  ]},
  { program:'Vim', category:'dev', color:'#019833', shortcuts:[
    { keys:['i'],                description:'Modo Insertar' },
    { keys:['Esc'],              description:'Modo Comando' },
    { keys:[':w'],               description:'Guardar' },
    { keys:[':q'],               description:'Salir' },
    { keys:[':wq'],              description:'Guardar y salir' },
    { keys:[':q!'],              description:'Salir sin guardar' },
    { keys:['h','j','k','l'],    description:'Mover cursor (izq, abajo, arriba, der)' },
    { keys:['w'],                description:'Siguiente palabra' },
    { keys:['b'],                description:'Palabra anterior' },
    { keys:['0'],                description:'Inicio de línea' },
    { keys:['$'],                description:'Final de línea' },
    { keys:['gg'],               description:'Inicio del archivo' },
    { keys:['G'],                description:'Final del archivo' },
    { keys:['dd'],               description:'Eliminar línea' },
    { keys:['yy'],               description:'Copiar línea (Yank)' },
    { keys:['p'],                description:'Pegar después del cursor' },
    { keys:['u'],                description:'Deshacer' },
    { keys:['Ctrl','r'],         description:'Rehacer' },
    { keys:['/','texto'],        description:'Buscar texto' },
    { keys:['n'],                description:'Siguiente resultado búsqueda' },
    { keys:['N'],                description:'Anterior resultado búsqueda' },
    { keys:['x'],                description:'Borrar carácter' },
    { keys:['A'],                description:'Insertar al final de la línea' },
    { keys:['o'],                description:'Nueva línea abajo' },
  ]},
  { program:'Terminal (Linux/Mac)', category:'dev', color:'#1a1a1a', shortcuts:[
    { keys:['Ctrl','C'],         description:'Interrumpir proceso actual' },
    { keys:['Ctrl','Z'],         description:'Suspender proceso (background)' },
    { keys:['Ctrl','D'],         description:'Cerrar sesión / EOF' },
    { keys:['Ctrl','L'],         description:'Limpiar pantalla' },
    { keys:['Ctrl','R'],         description:'Buscar en historial' },
    { keys:['Tab'],              description:'Autocompletar' },
    { keys:['↑','↓'],            description:'Navegar historial de comandos' },
    { keys:['Ctrl','A'],         description:'Ir al inicio de la línea' },
    { keys:['Ctrl','E'],         description:'Ir al final de la línea' },
    { keys:['Ctrl','U'],         description:'Borrar desde cursor al inicio' },
    { keys:['Ctrl','K'],         description:'Borrar desde cursor al final' },
    { keys:['Ctrl','W'],         description:'Borrar palabra anterior' },
    { keys:['Alt','B'],          description:'Mover cursor una palabra atrás' },
    { keys:['Alt','F'],          description:'Mover cursor una palabra adelante' },
    { keys:['!!'],               description:'Repetir último comando' },
  ]},
  { program:'CMD (Windows)', category:'dev', color:'#012456', shortcuts:[
    { keys:['↑','↓'],            description:'Navegar historial de comandos' },
    { keys:['Tab'],              description:'Autocompletar nombre de archivo' },
    { keys:['Ctrl','C'],         description:'Cancelar proceso en ejecución' },
    { keys:['Ctrl','A'],         description:'Seleccionar todo el texto' },
    { keys:['Ctrl','F'],         description:'Buscar texto en la consola' },
    { keys:['F7'],               description:'Ver historial de comandos' },
    { keys:['cls'],              description:'Limpiar pantalla (comando)' },
    { keys:['Alt','Enter'],      description:'Pantalla completa / ventana' },
    { keys:['F3'],               description:'Repetir último comando' },
    { keys:['Ctrl','M'],         description:'Modo marcación (para copiar)' },
  ]},
  { program:'Wireshark', category:'dev', color:'#1e5da3', shortcuts:[
    { keys:['Ctrl','K'],         description:'Iniciar captura' },
    { keys:['Ctrl','E'],         description:'Detener captura' },
    { keys:['Ctrl','F'],         description:'Buscar paquete' },
    { keys:['Ctrl','G'],         description:'Ir a paquete por número' },
    { keys:['Ctrl','R'],         description:'Recargar archivo de captura' },
    { keys:['Ctrl','D'],         description:'Marcar/Desmarcar paquete' },
    { keys:['Ctrl','Shift','N'], description:'Siguiente paquete marcado' },
    { keys:['Ctrl','M'],         description:'Aplicar como filtro seleccionado' },
    { keys:['Ctrl','T'],         description:'Seguir stream TCP' },
    { keys:['Ctrl','N'],         description:'Próximo paquete en conversación' },
    { keys:['Ctrl','B'],         description:'Paquete previo en conversación' },
  ]},
  { program:'Zabbix (Web UI)', category:'dev', color:'#d40000', shortcuts:[
    { keys:['Alt','A'],          description:'Ir a Alertas' },
    { keys:['Alt','D'],          description:'Ir a Dashboard' },
    { keys:['Alt','M'],          description:'Ir a Monitorización' },
    { keys:['Alt','P'],          description:'Ir a Problemas activos' },
    { keys:['Ctrl','F'],         description:'Buscar host en tabla' },
    { keys:['F5'],               description:'Refrescar vista actual' },
    { keys:['?'],                description:'Ver atajos disponibles' },
  ]},
  { program:'Sublime Text', category:'dev', color:'#272822', shortcuts:[
    { keys:['Ctrl','Shift','P'], description:'Paleta de comandos' },
    { keys:['Ctrl','P'],         description:'Ir a archivo' },
    { keys:['Ctrl','R'],         description:'Ir a símbolo' },
    { keys:['Ctrl','G'],         description:'Ir a línea' },
    { keys:['Ctrl','D'],         description:'Seleccionar palabra (repetir para sig.)' },
    { keys:['Ctrl','L'],         description:'Seleccionar línea' },
    { keys:['Ctrl','Shift','D'], description:'Duplicar línea' },
    { keys:['Ctrl','Shift','K'], description:'Borrar línea' },
    { keys:['Ctrl','/'],         description:'Comentar línea' },
    { keys:['Ctrl','J'],         description:'Unir líneas' },
    { keys:['Alt','. '],         description:'Cerrar etiqueta HTML' },
  ]},
  { program:'Android Studio', category:'dev', color:'#3DDC84', shortcuts:[
    { keys:['Shift','Shift'],    description:'Buscar en todo' },
    { keys:['Ctrl','N'],         description:'Ir a clase' },
    { keys:['Ctrl','Shift','N'], description:'Ir a archivo' },
    { keys:['Alt','Enter'],      description:'Mostrar acciones de intención' },
    { keys:['Ctrl','Alt','L'],   description:'Reformatear código' },
    { keys:['Ctrl','D'],         description:'Duplicar línea' },
    { keys:['Shift','F6'],       description:'Renombrar' },
    { keys:['Ctrl','Shift','F7'],description:'Resaltar usos en archivo' },
    { keys:['F9'],               description:'Continuar programa (Debug)' },
    { keys:['Ctrl','F8'],        description:'Alternar Breakpoint' },
  ]},
  { program:'Xcode', category:'dev', color:'#157EFB', shortcuts:[
    { keys:['Cmd','R'],          description:'Ejecutar App' },
    { keys:['Cmd','B'],          description:'Compilar (Build)' },
    { keys:['Cmd','.'],          description:'Detener ejecución' },
    { keys:['Cmd','Shift','O'],  description:'Apertura rápida' },
    { keys:['Cmd','Shift','J'],  description:'Revelar en Navegador de Proyectos' },
    { keys:['Cmd','/'],          description:'Comentar línea' },
    { keys:['Cmd','['],          description:'Mover sangría a la izquierda' },
    { keys:['Cmd',']'],          description:'Mover sangría a la derecha' },
    { keys:['Ctrl','I'],         description:'Re-indentar selección' },
  ]},
  { program:'PyCharm', category:'dev', color:'#21D789', shortcuts:[
    { keys:['Shift','F10'],      description:'Ejecutar' },
    { keys:['Shift','F9'],       description:'Depurar (Debug)' },
    { keys:['Alt','Shift','E'],  description:'Ejecutar selección en consola' },
    { keys:['Ctrl','Alt','S'],   description:'Abrir Configuración' },
    { keys:['Ctrl','Q'],         description:'Documentación rápida' },
    { keys:['Ctrl','P'],         description:'Información de parámetros' },
    { keys:['Alt','Ins'],        description:'Generar código' },
  ]},
  { program:'Postman', category:'dev', color:'#ff6c37', shortcuts:[
    { keys:['Ctrl','Enter'],     description:'Enviar solicitud' },
    { keys:['Ctrl','S'],         description:'Guardar solicitud' },
    { keys:['Ctrl','N'],         description:'Nueva solicitud' },
    { keys:['Ctrl','Shift','L'], description:'Alternar consola' },
    { keys:['Ctrl','Shift','C'], description:'Copiar respuesta' },
    { keys:['Ctrl','Alt','E'],   description:'Exportar colección' },
    { keys:['Ctrl','Alt','I'],   description:'Importar colección' },
    { keys:['Ctrl','Alt','G'],   description:'Generar código de solicitud' },
    { keys:['Ctrl','Shift','R'], description:'Limpiar cookies/caché' },
  ]},
  { program:'SQL Server', category:'dev', color:'#CC2927', shortcuts:[
    { keys:['F5'],               description:'Ejecutar consulta' },
    { keys:['Ctrl','E'],         description:'Ejecutar selección' },
    { keys:['Ctrl','N'],         description:'Nueva consulta' },
    { keys:['Ctrl','L'],         description:'Mostrar plan de ejecución estimado' },
    { keys:['Ctrl','M'],         description:'Incluir plan de ejecución real' },
    { keys:['Ctrl','K','Ctrl','C'],description:'Comentar bloque' },
    { keys:['Ctrl','K','Ctrl','U'],description:'Descomentar bloque' },
    { keys:['Ctrl','R'],         description:'Mostrar/Ocultar panel de resultados' },
    { keys:['Alt','Shift','↑/↓'], description:'Selección en bloque' },
    { keys:['F7'],               description:'Explorador de objetos' },
  ]},
  { program:'MongoDB', category:'dev', color:'#13aa52', shortcuts:[
    { keys:['it'],               description:'Iterar sobre cursor' },
    { keys:['cls'],              description:'Limpiar pantalla de shell' },
    { keys:['Ctrl','C'],         description:'Cancelar operación actual' },
    { keys:['use <db>'],         description:'Cambiar de base de datos' },
    { keys:['db.stats()'],       description:'Estadísticas de la BD' },
    { keys:['db.help()'],        description:'Mostrar ayuda de comandos' },
  ]},
  { program:'IntelliJ IDEA', category:'dev', color:'#000', shortcuts:[
    { keys:['Shift','Shift'],    description:'Buscar en todo' },
    { keys:['Ctrl','N'],         description:'Ir a clase' },
    { keys:['Ctrl','Shift','N'], description:'Ir a archivo' },
    { keys:['Alt','Enter'],      description:'Mostrar acciones de intención' },
    { keys:['Ctrl','Alt','L'],   description:'Reformatear código' },
    { keys:['Ctrl','D'],         description:'Duplicar línea' },
    { keys:['Ctrl','Y'],         description:'Eliminar línea' },
    { keys:['Ctrl','Shift','Enter'],description:'Completar sentencia' },
    { keys:['Alt','Ins'],        description:'Generar código' },
    { keys:['Ctrl','Shift','Space'],description:'Autocompletado inteligente' },
    { keys:['Shift','F6'],       description:'Cambiar nombre' },
  ]},

  // ── NAVEGACIÓN WEB ──────────────────────────────────────
  { program:'Chrome / Brave', category:'web', color:'#4285f4', shortcuts:[
    { keys:['Ctrl','T'],         description:'Nueva pestaña' },
    { keys:['Ctrl','Shift','T'], description:'Reabrir última pestaña cerrada' },
    { keys:['Ctrl','W'],         description:'Cerrar pestaña actual' },
    { keys:['Ctrl','N'],         description:'Nueva ventana' },
    { keys:['Ctrl','Shift','N'], description:'Nueva ventana de incógnito' },
    { keys:['Ctrl','L'],         description:'Enfocar barra de direcciones' },
    { keys:['Ctrl','F'],         description:'Buscar en la página' },
    { keys:['Ctrl','R'],         description:'Recargar página' },
    { keys:['Ctrl','Shift','R'], description:'Recargar forzando caché' },
    { keys:['Ctrl','H'],         description:'Ver historial' },
    { keys:['Ctrl','J'],         description:'Ver descargas' },
    { keys:['Ctrl','D'],         description:'Guardar en Marcadores' },
    { keys:['F12'],              description:'Herramientas de Desarrollador' },
    { keys:['Ctrl','+'],         description:'Aumentar Zoom' },
    { keys:['Ctrl','-'],         description:'Reducir Zoom' },
    { keys:['Ctrl','0'],         description:'Restablecer Zoom' },
    { keys:['Alt','←'],          description:'Atrás' },
    { keys:['Alt','→'],          description:'Adelante' },
    { keys:['Ctrl','Shift','Delete'], description:'Borrar datos de navegación' },
    { keys:['Ctrl','Enter'],     description:'Añadir .com a la dirección' },
    { keys:['Ctrl','Shift','B'], description:'Mostrar/ocultar barra marcadores' },
  ]},
  { program:'Firefox', category:'web', color:'#ff711f', shortcuts:[
    { keys:['Ctrl','T'],         description:'Nueva pestaña' },
    { keys:['Ctrl','W'],         description:'Cerrar pestaña' },
    { keys:['Ctrl','Shift','T'], description:'Reabrir pestaña cerrada' },
    { keys:['Ctrl','L'],         description:'Enfocar barra de direcciones' },
    { keys:['Ctrl','K'],         description:'Enfocar barra de búsqueda' },
    { keys:['Ctrl','Shift','P'], description:'Nueva ventana privada' },
    { keys:['Ctrl','F'],         description:'Buscar en página' },
    { keys:['Ctrl','R'],         description:'Recargar' },
    { keys:['Ctrl','Shift','R'], description:'Recargar (sin caché)' },
    { keys:['F12'],              description:'Herramientas de Desarrollador' },
  ]},
  { program:'Slack', category:'office', color:'#4a154b', shortcuts:[
    { keys:['Ctrl','K'],         description:'Salto rápido (Quick Switcher)' },
    { keys:['Ctrl','F'],         description:'Buscar en mensajes' },
    { keys:['Ctrl','Shift','A'], description:'Ver todos los hilos' },
    { keys:['Ctrl','Shift','M'], description:'Ver menciones y reacciones' },
    { keys:['Alt','↑/↓'],        description:'Navegar entre canales' },
    { keys:['Esc'],              description:'Marcar todo como leído' },
    { keys:['Ctrl','/'],         description:'Ver atajos de teclado' },
    { keys:['Ctrl','Shift','U'], description:'Subir archivo' },
  ]},
  { program:'Discord', category:'office', color:'#5865F2', shortcuts:[
    { keys:['Ctrl','K'],         description:'Salto rápido' },
    { keys:['Ctrl','Shift','M'], description:'Silenciar micrófono' },
    { keys:['Ctrl','Shift','D'], description:'Ensordecer' },
    { keys:['Alt','↑/↓'],        description:'Navegar entre canales' },
    { keys:['Alt','Shift','↑/↓'],description:'Navegar canales con mensajes' },
    { keys:['Esc'],              description:'Marcar canal como leído' },
    { keys:['Shift','Esc'],      description:'Marcar servidor como leído' },
    { keys:['Ctrl','/'],         description:'Ver atajos de teclado' },
  ]},
  { program:'Trello', category:'office', color:'#0079bf', shortcuts:[
    { keys:['N'],                description:'Nueva tarjeta' },
    { keys:['Enter'],            description:'Abrir tarjeta' },
    { keys:['Esc'],              description:'Cerrar tarjeta' },
    { keys:['C'],                description:'Archivar tarjeta' },
    { keys:['D'],                description:'Añadir fecha de vencimiento' },
    { keys:['L'],                description:'Abrir etiquetas' },
    { keys:['M'],                description:'Añadir/quitar miembros' },
    { keys:['Space'],            description:'Asignarme a la tarjeta' },
    { keys:['?'],                description:'Ver todos los atajos' },
  ]},
  { program:'Notion', category:'office', color:'#191919', shortcuts:[
    { keys:['Ctrl','P'],         description:'Búsqueda rápida / global' },
    { keys:['Ctrl','N'],         description:'Nueva página' },
    { keys:['Ctrl','Shift','L'], description:'Modo oscuro / claro' },
    { keys:['/'],                description:'Comandos / Menú de bloques' },
    { keys:['Ctrl','['],         description:'Ir atrás' },
    { keys:['Ctrl',']'],         description:'Ir adelante' },
    { keys:['Ctrl','Shift','1-9'],description:'Convertir en encabezado H1-H9' },
    { keys:['Ctrl','Alt','T'],   description:'Expandir/Contraer todos los toggles' },
    { keys:['Ctrl','Shift','Enter'],description:'Abrir en nueva pestaña' },
    { keys:['Ctrl','\\'],        description:'Ocultar/mostrar Sidebar' },
    { keys:['Ctrl','Enter'],     description:'Abrir página seleccionada' },
    { keys:['Ctrl','D'],         description:'Duplicar bloque' },
    { keys:['Ctrl','Shift','M'], description:'Comentar selección' },
    { keys:['[ ]'],              description:'Crear casilla To-do' },
    { keys:['Ctrl','Shift','H'], description:'Resaltar texto (highlight)' },
    { keys:['Ctrl','Shift','S'], description:'Añadir a favoritos' },
  ]},

  // ── OFIMÁTICA ────────────────────────────────────────────
  { program:'Excel', category:'office', color:'#1e6f3e', shortcuts:[
    { keys:['F2'],                description:'Editar celda activa' },
    { keys:['F4'],                description:'Repetir última acción / Alternar referencia ($A$1)' },
    { keys:['F9'],                description:'Calcular todas las hojas' },
    { keys:['F11'],               description:'Crear gráfico en nueva hoja' },
    { keys:['Alt','='],           description:'Autosuma' },
    { keys:['Alt','Enter'],       description:'Salto de línea dentro de celda' },
    { keys:['Ctrl',';'],          description:'Insertar fecha actual' },
    { keys:['Ctrl','Shift',':'],  description:'Insertar hora actual' },
    { keys:['Ctrl','Shift','~'],  description:'Formato General' },
    { keys:['Ctrl','Shift','$'],  description:'Formato Moneda' },
    { keys:['Ctrl','Shift','%'],  description:'Formato Porcentaje' },
    { keys:['Ctrl','Shift','!'],  description:'Formato Número con decimales' },
    { keys:['Ctrl','1'],          description:'Formato de Celdas' },
    { keys:['Ctrl','T'],          description:'Crear Tabla' },
    { keys:['Ctrl','Shift','L'],  description:'Activar/Desactivar Filtros' },
    { keys:['Ctrl','Space'],      description:'Seleccionar columna completa' },
    { keys:['Shift','Space'],     description:'Seleccionar fila completa' },
    { keys:['Ctrl','+'],          description:'Insertar celdas/filas/columnas' },
    { keys:['Ctrl','-'],          description:'Eliminar celdas/filas/columnas' },
    { keys:['Ctrl','9'],          description:'Ocultar filas seleccionadas' },
    { keys:['Ctrl','0'],          description:'Ocultar columnas seleccionadas' },
    { keys:['Ctrl','Shift','('],  description:'Mostrar filas ocultas' },
    { keys:['Ctrl','Shift',')'],  description:'Mostrar columnas ocultas' },
    { keys:['Ctrl','PgUp/PgDn'],  description:'Cambiar entre pestañas de hoja' },
    { keys:['Ctrl','Arrow'],      description:'Ir al borde de la región de datos' },
    { keys:['Ctrl','Shift','Arrow'], description:'Seleccionar hasta el borde de los datos' },
    { keys:['Ctrl','Home'],       description:'Ir a la celda A1' },
    { keys:['Ctrl','End'],        description:'Ir a la última celda con datos' },
    { keys:['Alt','F1'],          description:'Crear gráfico incrustado' },
    { keys:['Ctrl','D'],          description:'Rellenar hacia abajo' },
    { keys:['Ctrl','R'],          description:'Rellenar hacia la derecha' },
  ]},
  { program:'Word', category:'office', color:'#2b579a', shortcuts:[
    { keys:['Ctrl','N'],          description:'Negrita' },
    { keys:['Ctrl','K'],          description:'Cursiva' },
    { keys:['Ctrl','S'],          description:'Subrayado' },
    { keys:['Ctrl','Shift','W'],  description:'Subrayar solo palabras' },
    { keys:['Ctrl','Shift','D'],  description:'Doble subrayado' },
    { keys:['Ctrl','E'],          description:'Centrar párrafo' },
    { keys:['Ctrl','J'],          description:'Justificar párrafo' },
    { keys:['Ctrl','Q'],          description:'Alinear a la izquierda' },
    { keys:['Ctrl','D'],          description:'Alinear a la derecha' },
    { keys:['Ctrl','Shift','>'],  description:'Aumentar tamaño de fuente' },
    { keys:['Ctrl','Shift','<'],  description:'Disminuir tamaño de fuente' },
    { keys:['Ctrl','Alt','1-3'],  description:'Aplicar Estilos de Título 1-3' },
    { keys:['Ctrl','Shift','N'],  description:'Aplicar estilo Normal' },
    { keys:['Ctrl','Enter'],      description:'Salto de página' },
    { keys:['Ctrl','Shift','Enter'], description:'Salto de columna' },
    { keys:['Ctrl','K'],          description:'Insertar Hipervínculo' },
    { keys:['Ctrl','B'],          description:'Buscar' },
    { keys:['Ctrl','L'],          description:'Reemplazar' },
    { keys:['F7'],                description:'Ortografía y gramática' },
    { keys:['Shift','F3'],        description:'Cambiar Mayúsculas/Minúsculas' },
    { keys:['Ctrl','Shift','C'],  description:'Copiar formato' },
    { keys:['Ctrl','Shift','V'],  description:'Pegar formato' },
    { keys:['Ctrl','Space'],      description:'Quitar formato manual' },
    { keys:['Alt','Shift','D'],   description:'Insertar fecha' },
    { keys:['Alt','Shift','T'],   description:'Insertar hora' },
  ]},
  { program:'PowerPoint', category:'office', color:'#b7472a', shortcuts:[
    { keys:['F5'],                description:'Iniciar presentación desde el principio' },
    { keys:['Shift','F5'],        description:'Iniciar desde diapositiva actual' },
    { keys:['Alt','F5'],          description:'Vista del Presentador' },
    { keys:['Esc'],               description:'Finalizar presentación' },
    { keys:['Ctrl','M'],          description:'Nueva diapositiva' },
    { keys:['Ctrl','D'],          description:'Duplicar objeto / diapositiva' },
    { keys:['Ctrl','G'],          description:'Agrupar objetos' },
    { keys:['Ctrl','Shift','G'],  description:'Desagrupar objetos' },
    { keys:['Ctrl','Arrow'],      description:'Mover objeto en incrementos pequeños' },
    { keys:['Ctrl','Shift','C'],  description:'Copiar atributos de forma' },
    { keys:['Ctrl','Shift','V'],  description:'Pegar atributos de forma' },
    { keys:['B'],                 description:'Pantalla negra (durante presentación)' },
    { keys:['W'],                 description:'Pantalla blanca (durante presentación)' },
    { keys:['Enter / Space'],     description:'Siguiente diapositiva' },
    { keys:['Backspace'],         description:'Diapositiva anterior' },
    { keys:['Num','Enter'],       description:'Ir a diapositiva número X' },
    { keys:['Ctrl','P'],          description:'Activar herramienta Pluma' },
    { keys:['Ctrl','A'],          description:'Activar herramienta Flecha' },
    { keys:['Ctrl','E'],          description:'Activar herramienta Borrador' },
  ]},
  { program:'Microsoft Teams', category:'office', color:'#4B53BC', shortcuts:[
    { keys:['Ctrl','Shift','M'], description:'Silenciar / Activar audio' },
    { keys:['Ctrl','Shift','O'], description:'Encender / Apagar cámara' },
    { keys:['Ctrl','Shift','K'], description:'Levantar / Bajar mano' },
    { keys:['Ctrl','N'],         description:'Nuevo chat' },
    { keys:['Ctrl','Shift','E'], description:'Compartir pantalla' },
    { keys:['Ctrl','E'],         description:'Ir a búsqueda' },
    { keys:['Ctrl','1-9'],       description:'Navegar en barra lateral' },
  ]},
  { program:'Zoom', category:'office', color:'#2D8CFF', shortcuts:[
    { keys:['Alt','A'],          description:'Silenciar / Activar audio' },
    { keys:['Alt','V'],          description:'Encender / Apagar video' },
    { keys:['Alt','S'],          description:'Compartir pantalla' },
    { keys:['Alt','R'],          description:'Grabar localmente' },
    { keys:['Alt','F'],          description:'Pantalla completa' },
    { keys:['Alt','H'],          description:'Mostrar / Ocultar chat' },
    { keys:['Alt','U'],          description:'Mostrar / Ocultar participantes' },
  ]},
  // ── STREAMING ─────────────────────────────────────────────
  { program:'OBS Studio', category:'streaming', color:'#1a1a2e', shortcuts:[
    { keys:['Ctrl','Shift','S'], description:'Iniciar / Detener Stream' },
    { keys:['Ctrl','Shift','R'], description:'Iniciar / Detener Grabación' },
    { keys:['Ctrl','Shift','P'], description:'Pausar grabación' },
    { keys:['Ctrl','Shift','M'], description:'Silenciar micrófono' },
    { keys:['Ctrl','M'],         description:'Silenciar audio de escritorio' },
    { keys:['F7'],               description:'Activar Studio Mode' },
    { keys:['Ctrl','Shift','F'], description:'Fuente en Pantalla Completa' },
    { keys:['Ctrl','1'],         description:'Cambiar a Escena 1' },
    { keys:['Ctrl','2'],         description:'Cambiar a Escena 2' },
    { keys:['Ctrl','3'],         description:'Cambiar a Escena 3' },
    { keys:['Ctrl','T'],         description:'Activar Cámara Virtual' },
    { keys:['Ctrl','Shift','B'], description:'Transición Start/Stop' },
  ]},
  { program:'Streamlabs', category:'streaming', color:'#09aaef', shortcuts:[
    { keys:['Ctrl','Shift','S'], description:'Iniciar / Detener Stream' },
    { keys:['Ctrl','Shift','R'], description:'Iniciar / Detener Grabación' },
    { keys:['Ctrl','T'],         description:'Cambiar a Escena siguiente' },
    { keys:['Alt','A'],          description:'Silenciar / activar Audio' },
    { keys:['Ctrl','D'],         description:'Abrir chat de donaciones' },
    { keys:['Ctrl','M'],         description:'Silenciar micrófono' },
    { keys:['Ctrl','1'],         description:'Escena 1' },
    { keys:['Ctrl','2'],         description:'Escena 2' },
    { keys:['Ctrl','Shift','T'], description:'Activar Cámara Virtual' },
  ]},
  { program:'Windows 11', category:'os', color:'#0078d4', shortcuts:[
    { keys:['Win','E'],          description:'Abrir Explorador de archivos' },
    { keys:['Win','D'],          description:'Mostrar Escritorio' },
    { keys:['Win','L'],          description:'Bloquear equipo' },
    { keys:['Win','R'],          description:'Abrir Ejecutar' },
    { keys:['Win','S'],          description:'Abrir Búsqueda' },
    { keys:['Win','I'],          description:'Abrir Configuración' },
    { keys:['Win','V'],          description:'Historial del portapapeles' },
    { keys:['Win','X'],          description:'Menú de acceso rápido' },
    { keys:['Win','Tab'],        description:'Vista de tareas' },
    { keys:['Alt','Tab'],        description:'Cambiar entre ventanas' },
    { keys:['Ctrl','Shift','Esc'],description:'Administrador de tareas' },
    { keys:['Win','↑'],          description:'Maximizar ventana' },
    { keys:['Win','←/→'],        description:'Ajustar ventana a los lados' },
    { keys:['Win','Shift','S'],  description:'Recorte de pantalla' },
    { keys:['Win','.',';'],      description:'Selector de Emojis' },
    { keys:['Win','Ctrl','D'],   description:'Crear escritorio virtual' },
    { keys:['Win','Ctrl','←/→'], description:'Cambiar entre escritorios virtuales' },
    { keys:['Win','Ctrl','F4'],  description:'Cerrar escritorio virtual actual' },
    { keys:['Win','G'],          description:'Abrir Xbox Game Bar' },
    { keys:['Win','Alt','R'],    description:'Iniciar/Detener grabación de pantalla' },
    { keys:['Win','K'],          description:'Abrir menú Conectar (Cast)' },
    { keys:['Win','A'],          description:'Abrir Configuración rápida' },
    { keys:['Win','N'],          description:'Abrir Centro de notificaciones y Calendario' },
    { keys:['Win','Shift','V'],  description:'Enfocar notificaciones' },
  ]},
  { program:'Spotify', category:'os', color:'#1db954', shortcuts:[
    { keys:['Espacio'],          description:'Reproducir / Pausa' },
    { keys:['Ctrl','→'],         description:'Siguiente canción' },
    { keys:['Ctrl','←'],         description:'Canción anterior' },
    { keys:['Ctrl','↑'],         description:'Subir volumen' },
    { keys:['Ctrl','↓'],         description:'Bajar volumen' },
    { keys:['Ctrl','L'],         description:'Repetir canción' },
    { keys:['Ctrl','S'],         description:'Modo aleatorio' },
  ]},
]; // ← Fin del array.
