// ══════════════════════════════════════════
// ICONOS SVG — logos originales
// ══════════════════════════════════════════
const ICONS = {
  // ── VIDEO ──
  'After Effects': `<svg viewBox="0 0 44 44"><rect width="44" height="44" rx="9" fill="#00005b"/><text x="22" y="30" text-anchor="middle" font-family="Georgia,serif" font-weight="900" font-size="22" fill="#9999FF">Ae</text></svg>`,
  'Premiere Pro': `<svg viewBox="0 0 44 44"><rect width="44" height="44" rx="9" fill="#1d1342"/><text x="22" y="30" text-anchor="middle" font-family="Georgia,serif" font-weight="900" font-size="22" fill="#E8D5A3">Pr</text></svg>`,
  'DaVinci Resolve': `<svg viewBox="0 0 44 44"><rect width="44" height="44" rx="9" fill="#1a1a1a"/><circle cx="22" cy="20" r="10" fill="none" stroke="#c8a535" stroke-width="2.5"/><circle cx="22" cy="20" r="4" fill="#c8a535"/><rect x="10" y="31" width="24" height="2.5" rx="1.2" fill="#c8a535"/><rect x="14" y="35" width="16" height="2" rx="1" fill="#c8a535" opacity=".6"/></svg>`,
  'CapCut': `<svg viewBox="0 0 44 44"><rect width="44" height="44" rx="9" fill="#000"/><path d="M13 22 C13 16 18 12 24 12 L24 17 C21 17 18 19 18 22 C18 25 21 27 24 27 L24 32 C18 32 13 28 13 22Z" fill="white"/><rect x="25" y="12" width="5" height="20" rx="2.5" fill="white"/><rect x="32" y="12" width="5" height="9" rx="2.5" fill="white"/><rect x="32" y="23" width="5" height="9" rx="2.5" fill="white"/></svg>`,
  'Sony Vegas Pro': `<svg viewBox="0 0 44 44"><rect width="44" height="44" rx="9" fill="#0070c0"/><text x="22" y="23" text-anchor="middle" font-family="Arial Black,sans-serif" font-weight="900" font-size="10" fill="white">VEGAS</text><text x="22" y="34" text-anchor="middle" font-family="Arial,sans-serif" font-size="7.5" fill="#aad4f5" letter-spacing="2">PRO</text></svg>`,
  'Final Cut Pro': `<svg viewBox="0 0 44 44"><rect width="44" height="44" rx="9" fill="#1c1c1e"/><path d="M10 14 L10 30 L14 30 L14 14Z" fill="#d4a017"/><path d="M16 22 L34 14 L34 30Z" fill="#d4a017"/></svg>`,

  // ── DISEÑO ──
  'Photoshop': `<svg viewBox="0 0 44 44"><rect width="44" height="44" rx="9" fill="#001d35"/><text x="22" y="30" text-anchor="middle" font-family="Georgia,serif" font-weight="900" font-size="22" fill="#31A8FF">Ps</text></svg>`,
  'Illustrator': `<svg viewBox="0 0 44 44"><rect width="44" height="44" rx="9" fill="#310000"/><text x="22" y="30" text-anchor="middle" font-family="Georgia,serif" font-weight="900" font-size="22" fill="#FF9A00">Ai</text></svg>`,
  'InDesign': `<svg viewBox="0 0 44 44"><rect width="44" height="44" rx="9" fill="#49021f"/><text x="22" y="30" text-anchor="middle" font-family="Georgia,serif" font-weight="900" font-size="22" fill="#FF3366">Id</text></svg>`,
  'Figma': `<svg viewBox="0 0 44 44"><rect width="44" height="44" rx="9" fill="#1e1e1e"/><rect x="15" y="7" width="14" height="14" rx="7" fill="#FF7262"/><rect x="15" y="21" width="14" height="14" rx="3" fill="#1ABCFE"/><rect x="7" y="14" width="14" height="14" rx="7" fill="#0ACF83"/><rect x="21" y="14" width="14" height="14" rx="7" fill="#A259FF"/></svg>`,
  'Krita': `<svg viewBox="0 0 44 44"><rect width="44" height="44" rx="9" fill="#17375e"/><path d="M22 6 L28 18 L38 20 L30 28 L32 38 L22 33 L12 38 L14 28 L6 20 L16 18Z" fill="#2980b9" opacity=".3"/><circle cx="22" cy="22" r="9" fill="none" stroke="#2980b9" stroke-width="2.5"/><path d="M22 13 Q28 18 22 22 Q16 26 22 31" stroke="#2980b9" stroke-width="2" fill="none" stroke-linecap="round"/></svg>`,
  'CorelDRAW': `<svg viewBox="0 0 44 44"><rect width="44" height="44" rx="9" fill="#006400"/><circle cx="22" cy="20" r="10" fill="none" stroke="#7ed957" stroke-width="2.5"/><circle cx="22" cy="20" r="5" fill="#7ed957"/><text x="22" y="36" text-anchor="middle" font-family="Arial,sans-serif" font-weight="900" font-size="7" fill="#7ed957" letter-spacing=".5">DRAW</text></svg>`,
  'Canva': `<svg viewBox="0 0 44 44"><rect width="44" height="44" rx="9" fill="#7d2ae8"/><circle cx="22" cy="22" r="12" fill="white" opacity=".15"/><text x="22" y="28" text-anchor="middle" font-family="Arial Black,sans-serif" font-weight="900" font-size="20" fill="white">C</text></svg>`,

  // ── AUDIO ──
  'FL Studio': `<svg viewBox="0 0 44 44"><rect width="44" height="44" rx="9" fill="#1a0a00"/><path d="M8 34 Q15 8 22 22 Q26 30 30 12 L36 34" stroke="#FF8C00" stroke-width="3" fill="none" stroke-linecap="round" stroke-linejoin="round"/><circle cx="22" cy="22" r="3" fill="#FF8C00"/></svg>`,
  'Audacity': `<svg viewBox="0 0 44 44"><rect width="44" height="44" rx="9" fill="#003f5c"/><rect x="7" y="26" width="5" height="12" rx="2.5" fill="#00aaff"/><rect x="14" y="18" width="5" height="20" rx="2.5" fill="#00aaff"/><rect x="21" y="10" width="5" height="28" rx="2.5" fill="#00ccff"/><rect x="28" y="16" width="5" height="22" rx="2.5" fill="#00aaff"/><rect x="35" y="22" width="3" height="16" rx="1.5" fill="#0088cc"/></svg>`,
  'Adobe Audition': `<svg viewBox="0 0 44 44"><rect width="44" height="44" rx="9" fill="#00005b"/><text x="22" y="30" text-anchor="middle" font-family="Georgia,serif" font-weight="900" font-size="22" fill="#00E4BB">Au</text></svg>`,
  'Ableton Live': `<svg viewBox="0 0 44 44"><rect width="44" height="44" rx="9" fill="#1a1a1a"/><rect x="7" y="7" width="9" height="9" rx="1.5" fill="white"/><rect x="19" y="7" width="9" height="9" rx="1.5" fill="white"/><rect x="31" y="7" width="6" height="9" rx="1.5" fill="#444"/><rect x="7" y="19" width="6" height="9" rx="1.5" fill="#444"/><rect x="16" y="19" width="9" height="9" rx="1.5" fill="white"/><rect x="28" y="19" width="9" height="9" rx="1.5" fill="white"/><rect x="7" y="31" width="9" height="6" rx="1.5" fill="white"/><rect x="19" y="31" width="6" height="6" rx="1.5" fill="#444"/><rect x="28" y="31" width="9" height="6" rx="1.5" fill="white"/></svg>`,
  'Logic Pro': `<svg viewBox="0 0 44 44"><rect width="44" height="44" rx="9" fill="#1c1c1e"/><circle cx="22" cy="22" r="13" fill="none" stroke="#555" stroke-width="2"/><path d="M15 22 L22 12 L29 22 L22 32Z" fill="white"/></svg>`,

  // ── 3D ──
  'Blender': `<svg viewBox="0 0 44 44"><rect width="44" height="44" rx="9" fill="#16130f"/><circle cx="27" cy="21" r="9" fill="none" stroke="#E67E22" stroke-width="3"/><circle cx="27" cy="21" r="3.5" fill="#E67E22"/><line x1="8" y1="21" x2="18" y2="21" stroke="#E67E22" stroke-width="3" stroke-linecap="round"/><line x1="18" y1="21" x2="13" y2="13" stroke="#E67E22" stroke-width="2.5" stroke-linecap="round"/><line x1="18" y1="21" x2="13" y2="30" stroke="#E67E22" stroke-width="2.5" stroke-linecap="round"/></svg>`,
  'Maya': `<svg viewBox="0 0 44 44"><rect width="44" height="44" rx="9" fill="#0b1a1d"/><text x="22" y="30" text-anchor="middle" font-family="Georgia,serif" font-weight="900" font-size="28" fill="#1DB8C8">M</text></svg>`,
  'Cinema 4D': `<svg viewBox="0 0 44 44"><rect width="44" height="44" rx="9" fill="#0a1628"/><circle cx="22" cy="22" r="12" fill="none" stroke="#004c97" stroke-width="3.5"/><circle cx="22" cy="22" r="6" fill="none" stroke="#1565c0" stroke-width="2"/><text x="22" y="26" text-anchor="middle" font-family="Arial,sans-serif" font-weight="900" font-size="8" fill="#5b9bd5">C4D</text></svg>`,
  'ZBrush': `<svg viewBox="0 0 44 44"><rect width="44" height="44" rx="9" fill="#2a2a2a"/><path d="M10 34 Q14 28 22 22 Q30 16 34 10" stroke="#cc6600" stroke-width="3" fill="none" stroke-linecap="round"/><path d="M10 10 Q14 16 22 22 Q30 28 34 34" stroke="#888" stroke-width="2" fill="none" stroke-linecap="round"/><circle cx="22" cy="22" r="3" fill="#cc6600"/></svg>`,
  'SketchUp': `<svg viewBox="0 0 44 44"><rect width="44" height="44" rx="9" fill="#b22222"/><path d="M22 8 L36 16 L36 28 L22 36 L8 28 L8 16Z" fill="none" stroke="white" stroke-width="2.5"/><path d="M8 16 L22 24 L36 16" stroke="white" stroke-width="2"/><line x1="22" y1="24" x2="22" y2="36" stroke="white" stroke-width="2"/></svg>`,
  'BluffTitler': `<svg viewBox="0 0 44 44"><rect width="44" height="44" rx="9" fill="#1c2e40"/><text x="22" y="20" text-anchor="middle" font-family="Arial,sans-serif" font-weight="900" font-size="8" fill="#7ecaff">BLUFF</text><text x="22" y="30" text-anchor="middle" font-family="Arial,sans-serif" font-weight="900" font-size="7" fill="#aaa">TITLER</text><path d="M10 33 L34 33" stroke="#7ecaff" stroke-width="1.5" stroke-linecap="round"/></svg>`,

  // ── INGENIERÍA ──
  'AutoCAD': `<svg viewBox="0 0 44 44"><rect width="44" height="44" rx="9" fill="#cc0000"/><path d="M22 8 L36 34 L28 34 L22 20 L16 34 L8 34Z" fill="white"/><rect x="12" y="28" width="20" height="2.5" rx="1" fill="#cc0000"/></svg>`,
  'SolidWorks': `<svg viewBox="0 0 44 44"><rect width="44" height="44" rx="9" fill="#C0392B"/><path d="M12 28 Q12 16 22 14 Q28 13 30 18" stroke="white" stroke-width="3" fill="none" stroke-linecap="round"/><path d="M32 16 Q32 28 22 30 Q16 31 14 26" stroke="white" stroke-width="3" fill="none" stroke-linecap="round"/></svg>`,
  'Revit': `<svg viewBox="0 0 44 44"><rect width="44" height="44" rx="9" fill="#1a3a6e"/><text x="22" y="30" text-anchor="middle" font-family="Georgia,serif" font-weight="900" font-size="24" fill="#5b9bd5">Rv</text></svg>`,
  'Matlab': `<svg viewBox="0 0 44 44"><rect width="44" height="44" rx="9" fill="#003f6b"/><path d="M7 34 Q13 10 20 24 Q24 32 28 12 L37 34" stroke="#E87722" stroke-width="3" fill="none" stroke-linecap="round" stroke-linejoin="round"/><path d="M7 34 Q13 16 20 24" stroke="#0090d8" stroke-width="1.5" fill="none" stroke-linecap="round"/></svg>`,
  'CATIA': `<svg viewBox="0 0 44 44"><rect width="44" height="44" rx="9" fill="#003087"/><path d="M22 10 C14 10 9 15 9 22 C9 29 14 34 22 34 C26 34 30 32 32 28" stroke="white" stroke-width="3" fill="none" stroke-linecap="round"/><path d="M29 14 L36 22 L29 30" stroke="#5b9bd5" stroke-width="2.5" fill="none" stroke-linecap="round" stroke-linejoin="round"/></svg>`,

  // ── MEDICINA ──
  'Anki': `<svg viewBox="0 0 44 44"><rect width="44" height="44" rx="9" fill="#1565c0"/><rect x="9" y="13" width="26" height="18" rx="5" fill="none" stroke="white" stroke-width="2.5"/><line x1="22" y1="17" x2="22" y2="27" stroke="white" stroke-width="2.5" stroke-linecap="round"/><line x1="14" y1="22" x2="30" y2="22" stroke="white" stroke-width="2.5" stroke-linecap="round"/></svg>`,
  'OsiriX / Horos': `<svg viewBox="0 0 44 44"><rect width="44" height="44" rx="9" fill="#2a2a2a"/><circle cx="22" cy="22" r="13" fill="none" stroke="#888" stroke-width="2.5"/><circle cx="22" cy="22" r="6" fill="none" stroke="#aaa" stroke-width="1.5"/><line x1="9" y1="22" x2="35" y2="22" stroke="#666" stroke-width="1"/><line x1="22" y1="9" x2="22" y2="35" stroke="#666" stroke-width="1"/><circle cx="22" cy="22" r="2" fill="#aaa"/></svg>`,
  'Complete Anatomy': `<svg viewBox="0 0 44 44"><rect width="44" height="44" rx="9" fill="#c0392b"/><path d="M22 8 C22 8 26 10 26 14 C26 17 24 18 22 18 C20 18 18 17 18 14 C18 10 22 8 22 8Z" fill="white"/><path d="M15 18 C13 20 12 24 13 28 L14 36 L22 33 L30 36 L31 28 C32 24 31 20 29 18 L26 17 C25 19 22 20 22 20 C22 20 19 19 18 17Z" fill="white" opacity=".9"/></svg>`,
  'PubMed': `<svg viewBox="0 0 44 44"><rect width="44" height="44" rx="9" fill="#005a8e"/><text x="22" y="23" text-anchor="middle" font-family="Arial Black,sans-serif" font-weight="900" font-size="13" fill="white">Pub</text><text x="22" y="35" text-anchor="middle" font-family="Arial Black,sans-serif" font-weight="900" font-size="13" fill="#7ec8e3">Med</text></svg>`,

  // ── DEV / IT ──
  'VS Code': `<svg viewBox="0 0 44 44"><rect width="44" height="44" rx="9" fill="#007ACC"/><path d="M31 9 L13 22 L31 36 L37 30 L22 22 L37 14Z" fill="white"/><path d="M7 17 L13 11 L22 22 L13 33 L7 27 L15 22Z" fill="white"/></svg>`,
  'Terminal (Linux/Mac)': `<svg viewBox="0 0 44 44"><rect width="44" height="44" rx="9" fill="#1a1a1a"/><rect x="8" y="10" width="28" height="24" rx="4" fill="none" stroke="#444" stroke-width="1.5"/><path d="M13 18 L19 22 L13 26" stroke="#00ff41" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round"/><line x1="21" y1="26" x2="31" y2="26" stroke="#00ff41" stroke-width="2" stroke-linecap="round"/></svg>`,
  'CMD (Windows)': `<svg viewBox="0 0 44 44"><rect width="44" height="44" rx="9" fill="#012456"/><rect x="8" y="10" width="28" height="24" rx="3" fill="#0C0C0C"/><rect x="10" y="12" width="24" height="4" rx="1" fill="#012456"/><path d="M12 22 L17 25 L12 28" stroke="#ccc" stroke-width="1.5" fill="none" stroke-linecap="round"/><line x1="19" y1="28" x2="27" y2="28" stroke="#ccc" stroke-width="1.5" stroke-linecap="round"/></svg>`,
  'Wireshark': `<svg viewBox="0 0 44 44"><rect width="44" height="44" rx="9" fill="#1a3a5c"/><path d="M7 32 Q12 8 18 22 Q22 32 26 12 L37 32" stroke="#00aaff" stroke-width="2.5" fill="none" stroke-linecap="round"/><path d="M7 32 Q12 14 18 22" stroke="#0066cc" stroke-width="1.5" fill="none" stroke-linecap="round"/><circle cx="18" cy="22" r="2.5" fill="#00aaff"/></svg>`,
  'Zabbix (Web UI)': `<svg viewBox="0 0 44 44"><rect width="44" height="44" rx="9" fill="#c0392b"/><path d="M10 12 L34 12 L20 22 L34 32 L10 32" stroke="white" stroke-width="3" fill="none" stroke-linecap="round" stroke-linejoin="round"/></svg>`,

  // ── OFIMÁTICA ──
  'Excel': `<svg viewBox="0 0 44 44"><rect width="44" height="44" rx="9" fill="#1e6f3e"/><path d="M7 10 L7 34 L25 34 L25 10Z" fill="#185C37"/><path d="M25 10 L37 10 L37 34 L25 34Z" fill="#21A366"/><line x1="25" y1="10" x2="25" y2="34" stroke="#107C41" stroke-width=".5"/><line x1="7" y1="22" x2="37" y2="22" stroke="#107C41" stroke-width=".5"/><path d="M12 14 L18 22 L12 30" stroke="white" stroke-width="2" fill="none" stroke-linecap="round"/><path d="M18 14 L12 22 L18 30" stroke="white" stroke-width="2" fill="none" stroke-linecap="round"/></svg>`,
  'Word': `<svg viewBox="0 0 44 44"><rect width="44" height="44" rx="9" fill="#2b579a"/><path d="M7 10 L7 34 L25 34 L25 10Z" fill="#1e4d8c"/><path d="M25 10 L37 10 L37 34 L25 34Z" fill="#2b6cb0"/><text x="13" y="26" font-family="Arial Black,sans-serif" font-weight="900" font-size="12" fill="white">W</text><path d="M26 16 L30 26 L34 16" stroke="white" stroke-width="1.5" fill="none" stroke-linecap="round" stroke-linejoin="round"/></svg>`,
  'PowerPoint': `<svg viewBox="0 0 44 44"><rect width="44" height="44" rx="9" fill="#b7472a"/><path d="M7 10 L7 34 L25 34 L25 10Z" fill="#9c3a1f"/><path d="M25 10 L37 10 L37 34 L25 34Z" fill="#c0502e"/><text x="14" y="26" font-family="Arial Black,sans-serif" font-weight="900" font-size="12" fill="white">P</text><path d="M28 16 L28 28 M28 22 L33 22" stroke="white" stroke-width="2" stroke-linecap="round"/></svg>`,
  'Notion': `<svg viewBox="0 0 44 44"><rect width="44" height="44" rx="9" fill="#fff"/><path d="M12 10 L12 34 L14 34 L14 17 L28 34 L32 34 L32 10 L30 10 L30 27 L16 10Z" fill="#191919"/></svg>`,
  'Slack': `<svg viewBox="0 0 44 44"><rect width="44" height="44" rx="9" fill="#4a154b"/><rect x="8" y="18" width="12" height="6" rx="3" fill="#E01E5A"/><rect x="8" y="10" width="6" height="14" rx="3" fill="#E01E5A"/><rect x="24" y="20" width="12" height="6" rx="3" fill="#36C5F0"/><rect x="30" y="20" width="6" height="14" rx="3" fill="#36C5F0"/><rect x="8" y="26" width="12" height="6" rx="3" fill="#2EB67D"/><rect x="8" y="26" width="6" height="14" rx="3" fill="#2EB67D"/><rect x="24" y="8" width="12" height="6" rx="3" fill="#ECB22E"/><rect x="30" y="8" width="6" height="14" rx="3" fill="#ECB22E"/></svg>`,

  // ── STREAMING ──
  'OBS Studio': `<svg viewBox="0 0 44 44"><rect width="44" height="44" rx="9" fill="#1a1a2e"/><circle cx="22" cy="22" r="14" fill="none" stroke="#302e31" stroke-width="3"/><circle cx="22" cy="22" r="9" fill="none" stroke="#6366f1" stroke-width="2.5"/><circle cx="22" cy="22" r="4" fill="#6366f1"/></svg>`,
  'Streamlabs': `<svg viewBox="0 0 44 44"><rect width="44" height="44" rx="9" fill="#09aaef"/><path d="M22 8 L33 24 L28 24 L28 36 L16 36 L16 24 L11 24Z" fill="white"/></svg>`,
};

// ═══════════════════════════════════════════════════════════
// CATEGORÍAS
// ═══════════════════════════════════════════════════════════
const CATEGORIES = [
  { id: 'all',         name: 'Todos los Programas',    icon: '🖥️' },
  { id: 'video',       name: 'Video / Post-producción', icon: '🎬' },
  { id: 'graphic',     name: 'Diseño y Arte Digital',   icon: '🎨' },
  { id: 'audio',       name: 'Producción de Audio',     icon: '🎵' },
  { id: '3d',          name: '3D y Animación',          icon: '🧊' },
  { id: 'engineering', name: 'Ingeniería y CAD',        icon: '⚙️' },
  { id: 'medicine',    name: 'Medicina y Estudio',      icon: '🩺' },
  { id: 'dev',         name: 'Sistemas / IT',           icon: '💻' },
  { id: 'office',      name: 'Ofimática',               icon: '📄' },
  { id: 'streaming',   name: 'Streaming',               icon: '📡' },
];

// ═══════════════════════════════════════════════════════════
// PROGRAMAS — añade nuevos objetos antes del cierre del array
// ═══════════════════════════════════════════════════════════
const PROGRAMS = [
  // ── VIDEO ──────────────────────────────────────────────
  { program:'CapCut', category:'video', color:'#111', shortcuts:[
    { keys:['B'],                description:'Cuchilla / Dividir clip' },
    { keys:['Ctrl','B'],         description:'Dividir en el cabezal' },
    { keys:['V'],                description:'Herramienta Selección' },
    { keys:['Ctrl','J'],         description:'Exportar Proyecto' },
    { keys:['Espacio'],          description:'Play / Pausa' },
    { keys:['I'],                description:'Marcar punto de entrada' },
    { keys:['O'],                description:'Marcar punto de salida' },
    { keys:['Ctrl','Z'],         description:'Deshacer' },
    { keys:['Ctrl','Y'],         description:'Rehacer' },
    { keys:['Delete'],           description:'Eliminar clip seleccionado' },
    { keys:['Alt','↑'],          description:'Subir nivel de pista' },
    { keys:['Alt','↓'],          description:'Bajar nivel de pista' },
    { keys:['Ctrl','R'],         description:'Velocidad del clip' },
    { keys:['Ctrl','C'],         description:'Copiar clip' },
    { keys:['Ctrl','V'],         description:'Pegar clip' },
    { keys:[','],                description:'Retroceder un frame' },
    { keys:['.'],                description:'Avanzar un frame' },
  ]},
  { program:'After Effects', category:'video', color:'#00005b', shortcuts:[
    { keys:['P'],                description:'Mostrar Posición' },
    { keys:['S'],                description:'Mostrar Escala' },
    { keys:['R'],                description:'Mostrar Rotación' },
    { keys:['T'],                description:'Mostrar Opacidad' },
    { keys:['A'],                description:'Mostrar Anchor Point' },
    { keys:['U'],                description:'Ver Keyframes activos' },
    { keys:['U','U'],            description:'Ver propiedades modificadas' },
    { keys:['F9'],               description:'Easy Ease (suavizado)' },
    { keys:['Ctrl','D'],         description:'Duplicar capa' },
    { keys:['Ctrl','Shift','C'], description:'Precomponer selección' },
    { keys:['Alt','['],          description:'Recortar inicio de capa' },
    { keys:['Alt',']'],          description:'Recortar fin de capa' },
    { keys:['Ctrl','K'],         description:'Ajustes de composición' },
    { keys:['0'],                description:'Preview RAM' },
    { keys:['Ctrl','Shift','D'], description:'Dividir capa' },
    { keys:['M'],                description:'Mostrar máscara' },
    { keys:['Ctrl','Alt','F'],   description:'Ajustar al tamaño de comp' },
    { keys:['L'],                description:'Mostrar Niveles de Audio' },
    { keys:['Ctrl','Shift','Y'], description:'Nueva capa sólida' },
    { keys:['Ctrl','Alt','T'],   description:'Time Stretch' },
    { keys: ['Ctrl','Alt','Shift','Y'], description: 'Ajustes sólidos' },
    { keys: ['Ctrl','Alt','Home'], description: 'Centrar Anchor Point' },
    { keys: ['Alt','Click (reloj)'], description: 'Activar expresiones' },
    { keys: ['Ctrl','Shift','Alt','V'], description: 'Pegar con keyframes' },
  ]},
  { program:'Premiere Pro', category:'video', color:'#1d1342', shortcuts:[
    { keys:['C'],                description:'Cuchilla (Razor)' },
    { keys:['V'],                description:'Herramienta Selección' },
    { keys:['Q'],                description:'Recorte Rizo Anterior' },
    { keys:['W'],                description:'Recorte Rizo Posterior' },
    { keys:['Ctrl','M'],         description:'Exportar Media' },
    { keys:['Shift','D'],        description:'Transición por defecto' },
    { keys:['Ctrl','K'],         description:'Corte en el cabezal' },
    { keys:['I'],                description:'Punto de entrada' },
    { keys:['O'],                description:'Punto de salida' },
    { keys:['Espacio'],          description:'Play / Pausa' },
    { keys:['Ctrl','Z'],         description:'Deshacer' },
    { keys:['Shift','1'],        description:'Ir a Ensamblaje' },
    { keys:['Shift','3'],        description:'Ir a Color' },
    { keys:['Ctrl','L'],         description:'Enlazar/desenlazar clip' },
    { keys:['G'],                description:'Velocidad/Duración del clip' },
    { keys:[','],                description:'Insertar en timeline' },
    { keys:['.'],                description:'Sobreescribir en timeline' },
    { keys:['Ctrl','Shift','E'], description:'Exportar cuadro' },
    { keys: ['Alt','Arrastrar'], description: 'Duplicar clip rápido' },
    { keys: ['Ctrl','D'], description: 'Transición de video' },
    { keys: ['Ctrl','Shift','D'], description: 'Transición de audio' },
    { keys: ['\\'], description: 'Ver toda la timeline' },
    { keys: ['Shift','K'], description: 'Avanzar 5 frames' },
    { keys: ['Shift','J'], description: 'Retroceder 5 frames' },
  ]},
  { program:'DaVinci Resolve', category:'video', color:'#1a1a1a', shortcuts:[
    { keys:['Alt','S'],          description:'Nuevo Nodo Serial' },
    { keys:['Alt','P'],          description:'Nuevo Nodo Paralelo' },
    { keys:['Alt','L'],          description:'Nuevo Nodo Layer' },
    { keys:['Shift','Z'],        description:'Ajustar Timeline a ventana' },
    { keys:['B'],                description:'Cuchilla (Blade)' },
    { keys:['A'],                description:'Selección estándar' },
    { keys:['T'],                description:'Modo recorte dinámico' },
    { keys:['Ctrl','F'],         description:'Pantalla Completa' },
    { keys:['Espacio'],          description:'Play / Pausa' },
    { keys:['D'],                description:'Activar/desactivar clip' },
    { keys:['Shift','S'],        description:'Stillframe para Color' },
    { keys:['Ctrl','Shift','H'], description:'Activar Highlight' },
    { keys:['Y'],                description:'Modo Edición selección' },
    { keys:['Ctrl','G'],         description:'Agrupar clips' },
    { keys:['Ctrl','R'],         description:'Invertir clip' },
    { keys:['J'],                description:'Reproducir hacia atrás' },
    { keys:['K'],                description:'Pausa' },
    { keys:['L'],                description:'Reproducir hacia adelante' },
    { keys:['Ctrl','Shift',','], description:'Exportar (Deliver)' },
  ]},
  { program:'Sony Vegas Pro', category:'video', color:'#0070c0', shortcuts:[
    { keys:['S'],                description:'Dividir en el cursor' },
    { keys:['M'],                description:'Insertar Marcador' },
    { keys:['Z'],                description:'Herramienta Zoom' },
    { keys:['Ctrl','Z'],         description:'Deshacer' },
    { keys:['Ctrl','M'],         description:'Exportar (Render As)' },
    { keys:['Espacio'],          description:'Play / Pausa' },
    { keys:['Ctrl','A'],         description:'Seleccionar todo' },
    { keys:['F4'],               description:'Propiedades del clip' },
    { keys:['Ctrl','E'],         description:'Abrir editor de audio' },
    { keys:['Alt','Delete'],     description:'Eliminar sin dejar hueco' },
    { keys:['Q'],                description:'Activar snapping' },
    { keys:['G'],                description:'Agrupar clips' },
    { keys:['D'],                description:'Herramienta Selección normal' },
    { keys:['T'],                description:'Dividir pistas automático' },
  ]},
  { program:'Final Cut Pro', category:'video', color:'#1a1a1a', shortcuts:[
    { keys:['B'],                description:'Cuchilla (Blade)' },
    { keys:['A'],                description:'Herramienta Selección' },
    { keys:['T'],                description:'Herramienta Recorte' },
    { keys:['P'],                description:'Herramienta Posición' },
    { keys:['R'],                description:'Herramienta Rango' },
    { keys:['Cmd','B'],          description:'Dividir en el cabezal' },
    { keys:['Cmd','E'],          description:'Exportar Share Master' },
    { keys:['Espacio'],          description:'Play / Pausa' },
    { keys:['Cmd','Z'],          description:'Deshacer' },
    { keys:['I'],                description:'Punto de entrada' },
    { keys:['O'],                description:'Punto de salida' },
    { keys:['Cmd','4'],          description:'Inspector' },
    { keys:['Shift','Z'],        description:'Ajustar Timeline' },
    { keys:['W'],                description:'Insertar en primario' },
    { keys:['Q'],                description:'Conectar al primario' },
    { keys:['J'],                description:'Play reversa' },
    { keys:['K'],                description:'Pausa' },
    { keys:['L'],                description:'Play adelante' },
    { keys:['Cmd','Shift','A'],  description:'Deseleccionar todo' },
  ]},

  // ── DISEÑO ─────────────────────────────────────────────
  { program:'Photoshop', category:'graphic', color:'#001d35', shortcuts:[
    { keys:['Ctrl','J'],             description:'Duplicar capa' },
    { keys:['Ctrl','T'],             description:'Transformación libre' },
    { keys:['B'],                    description:'Pincel' },
    { keys:['E'],                    description:'Borrador' },
    { keys:['L'],                    description:'Lazo' },
    { keys:['W'],                    description:'Varita mágica / Selección rápida' },
    { keys:['Ctrl','Shift','Alt','E'],description:'Combinar en nueva capa' },
    { keys:['X'],                    description:'Intercambiar color fondo/frente' },
    { keys:['D'],                    description:'Restablecer colores negro/blanco' },
    { keys:['Ctrl','L'],             description:'Niveles' },
    { keys:['Ctrl','U'],             description:'Tono / Saturación' },
    { keys:['Ctrl','M'],             description:'Curvas' },
    { keys:['Ctrl','B'],             description:'Balance de Color' },
    { keys:['Ctrl','G'],             description:'Agrupar capas' },
    { keys:['Ctrl','Shift','I'],     description:'Invertir selección' },
    { keys:['Alt','Delete'],         description:'Rellenar con color frontal' },
    { keys:['Ctrl','Delete'],        description:'Rellenar con color de fondo' },
    { keys:['Ctrl','Alt','Z'],       description:'Paso atrás en historial' },
    { keys:['['],                    description:'Reducir tamaño de pincel' },
    { keys:[']'],                    description:'Aumentar tamaño de pincel' },
    { keys:['Ctrl','Shift','N'],     description:'Nueva capa vacía' },
    { keys: ['Ctrl','Alt','G'], description: 'Máscara de recorte' },
    { keys: ['Ctrl','Shift','Alt','N'], description: 'Nueva capa sin diálogo' },
    { keys: ['Ctrl','Alt','Shift','S'], description: 'Guardar para web' },
    { keys: ['Alt','Scroll'], description: 'Zoom suave' },
    { keys: ['Shift','Backspace'], description: 'Relleno inteligente' },
    { keys: ['Ctrl','Alt','I'], description: 'Tamaño de imagen' },
  ]},
  { program:'Illustrator', category:'graphic', color:'#300', shortcuts:[
    { keys:['P'],                description:'Herramienta Pluma' },
    { keys:['V'],                description:'Herramienta Selección' },
    { keys:['A'],                description:'Selección Directa' },
    { keys:['N'],                description:'Herramienta Lápiz' },
    { keys:['Shift','M'],        description:'Generador de Formas' },
    { keys:['Ctrl','Shift','O'], description:'Convertir texto a trazado' },
    { keys:['Ctrl','G'],         description:'Agrupar' },
    { keys:['Ctrl','Shift','G'], description:'Desagrupar' },
    { keys:['Ctrl','Alt','B'],   description:'Mezcla (Blend Make)' },
    { keys:['Ctrl','7'],         description:'Crear Máscara de Recorte' },
    { keys:['Ctrl','Alt','7'],   description:'Soltar Máscara de Recorte' },
    { keys:['R'],                description:'Rotar' },
    { keys:['S'],                description:'Escalar' },
    { keys:['E'],                description:'Borrador' },
    { keys:['Ctrl','Shift','P'], description:'Colocar imagen' },
    { keys:['Ctrl','Shift','E'], description:'Exportar' },
    { keys:['K'],                description:'Bote de pintura dinámica' },
    { keys: ['Ctrl','Y'], description: 'Vista contorno' },
    { keys: ['Ctrl','Shift','B'], description: 'Opciones de mezcla' },
    { keys: ['Alt','Drag'], description: 'Duplicar objeto' },
    { keys: ['Ctrl','2'], description: 'Bloquear selección' },
    { keys: ['Ctrl','Alt','2'], description: 'Desbloquear todo' },
  ]},
  { program:'InDesign', category:'graphic', color:'#49021f', shortcuts:[
    { keys:['T'],                description:'Herramienta Texto' },
    { keys:['F'],                description:'Marco Rectangular' },
    { keys:['V'],                description:'Herramienta Selección' },
    { keys:['A'],                description:'Selección Directa' },
    { keys:['Ctrl','Shift','P'], description:'Colocar imagen' },
    { keys:['W'],                description:'Vista Previa' },
    { keys:['Ctrl','B'],         description:'Opciones de Marco de Texto' },
    { keys:['Ctrl','Shift','D'], description:'Ver caracteres ocultos' },
    { keys:['Ctrl','E'],         description:'Exportar (PDF, EPUB…)' },
    { keys:['Ctrl','G'],         description:'Agrupar objetos' },
    { keys:['Ctrl','Alt','N'],   description:'Nueva página' },
    { keys:['Shift','PageDown'], description:'Ir a página siguiente' },
    { keys:['Ctrl','Shift','H'], description:'Mostrar/ocultar guías' },
  ]},
  { program:'Figma', category:'graphic', color:'#1e1e1e', shortcuts:[
    { keys:['F'],                description:'Marco (Frame)' },
    { keys:['R'],                description:'Rectángulo' },
    { keys:['T'],                description:'Texto' },
    { keys:['V'],                description:'Herramienta Mover' },
    { keys:['K'],                description:'Escalar' },
    { keys:['P'],                description:'Pluma (Pen)' },
    { keys:['O'],                description:'Elipse' },
    { keys:['L'],                description:'Línea' },
    { keys:['I'],                description:'Cuentagotas (Color picker)' },
    { keys:['Ctrl','G'],         description:'Agrupar' },
    { keys:['Ctrl','Alt','G'],   description:'Marco con selección' },
    { keys:['Shift','A'],        description:'Auto Layout' },
    { keys:['Ctrl','D'],         description:'Duplicar' },
    { keys:['Ctrl','Shift','H'], description:'Esconder/mostrar UI' },
    { keys:['Ctrl','\\'],        description:'Mostrar/ocultar panel' },
    { keys:['Ctrl','Shift','K'], description:'Reemplazar imagen' },
    { keys:['Ctrl','E'],         description:'Aplanar selección' },
    { keys:['Ctrl','Alt','C'],   description:'Copiar propiedades CSS' },
  ]},
  { program:'Krita', category:'graphic', color:'#17375e', shortcuts:[
    { keys:['B'],                description:'Pincel' },
    { keys:['E'],                description:'Modo Borrador' },
    { keys:['Shift','I'],        description:'Selector de Color (rueda)' },
    { keys:['M'],                description:'Espejar lienzo' },
    { keys:['Ctrl','U'],         description:'Tono / Saturación' },
    { keys:['Ctrl','R'],         description:'Transformación libre' },
    { keys:['Ctrl','J'],         description:'Duplicar capa' },
    { keys:['Ctrl','Shift','N'], description:'Nueva capa' },
    { keys:['['],                description:'Reducir tamaño de pincel' },
    { keys:[']'],                description:'Aumentar tamaño de pincel' },
    { keys:['4'],                description:'Rotar lienzo izquierda' },
    { keys:['6'],                description:'Rotar lienzo derecha' },
    { keys:['Ctrl','L'],         description:'Niveles' },
  ]},
  { program:'CorelDRAW', category:'graphic', color:'#006400', shortcuts:[
    { keys:['F10'],              description:'Herramienta Forma' },
    { keys:['F6'],               description:'Rectángulo' },
    { keys:['F7'],               description:'Elipse' },
    { keys:['P'],                description:'Pluma (Bezier)' },
    { keys:['Ctrl','L'],         description:'Combinar objetos' },
    { keys:['Ctrl','K'],         description:'Separar objetos combinados' },
    { keys:['Ctrl','G'],         description:'Agrupar' },
    { keys:['Ctrl','U'],         description:'Desagrupar' },
    { keys:['Ctrl','E'],         description:'Exportar' },
    { keys:['Ctrl','I'],         description:'Importar' },
    { keys:['Ctrl','Shift','A'], description:'Herramienta Alineación' },
    { keys:['F11'],              description:'Relleno de degradado' },
    { keys:['F12'],              description:'Propiedades del contorno' },
    { keys:['G'],                description:'Relleno interactivo' },
  ]},
  { program:'Canva', category:'graphic', color:'#7d2ae8', shortcuts:[
    { keys:['T'],                description:'Añadir texto' },
    { keys:['R'],                description:'Añadir rectángulo' },
    { keys:['C'],                description:'Añadir círculo' },
    { keys:['Ctrl','D'],         description:'Duplicar elemento' },
    { keys:['Ctrl','G'],         description:'Agrupar elementos' },
    { keys:['Ctrl','Shift','G'], description:'Desagrupar elementos' },
    { keys:['Ctrl','Z'],         description:'Deshacer' },
    { keys:['Ctrl','Shift','Z'], description:'Rehacer' },
    { keys:['Delete'],           description:'Eliminar elemento' },
    { keys:['Ctrl','A'],         description:'Seleccionar todo' },
    { keys:['Alt','N'],          description:'Nueva página' },
    { keys:['Ctrl','F'],         description:'Buscar elemento' },
    { keys:['Ctrl','→'],         description:'Enviar al frente' },
    { keys:['Ctrl','←'],         description:'Enviar al fondo' },
  ]},

  // ── AUDIO ──────────────────────────────────────────────
  { program:'FL Studio', category:'audio', color:'#1a0a00', shortcuts:[
    { keys:['F9'],               description:'Abrir Mezclador (Mixer)' },
    { keys:['F7'],               description:'Abrir Piano Roll' },
    { keys:['F5'],               description:'Abrir Playlist' },
    { keys:['F6'],               description:'Abrir Step Sequencer' },
    { keys:['Ctrl','L'],         description:'Asignar canal al Mixer' },
    { keys:['Espacio'],          description:'Play / Pausa' },
    { keys:['Enter'],            description:'Reproducir desde inicio' },
    { keys:['Ctrl','Z'],         description:'Deshacer' },
    { keys:['Ctrl','S'],         description:'Guardar proyecto' },
    { keys:['Ctrl','R'],         description:'Exportar como WAV' },
    { keys:['Ctrl','Shift','S'], description:'Guardar nueva versión' },
    { keys:['Ctrl','P'],         description:'Piano Roll del canal actual' },
    { keys:['Ctrl','M'],         description:'Abrir MIDI Settings' },
    { keys:['Alt','G'],          description:'Abrir generador seleccionado' },
    { keys: ['Ctrl','Click'], description: 'Selección múltiple' },
    { keys: ['Shift','Click'], description: 'Selección por rango' },
    { keys: ['Alt','Scroll'], description: 'Zoom timeline' },
    { keys: ['Ctrl','↑','↓'], description: 'Mover notas' },
    { keys: ['Alt','Q'], description: 'Quantize' },
  ]},
  { program:'Audacity', category:'audio', color:'#003f5c', shortcuts:[
    { keys:['R'],                description:'Grabar' },
    { keys:['Espacio'],          description:'Play / Pausa' },
    { keys:['Ctrl','I'],         description:'Dividir clip' },
    { keys:['Ctrl','L'],         description:'Silenciar selección' },
    { keys:['Ctrl','Shift','N'], description:'Nueva pista' },
    { keys:['Z'],                description:'Cruce por cero' },
    { keys:['Ctrl','A'],         description:'Seleccionar todo' },
    { keys:['Ctrl','E'],         description:'Exportar audio' },
    { keys:['F1'],               description:'Herramienta Selección' },
    { keys:['F2'],               description:'Herramienta Envolvente' },
    { keys:['Ctrl','D'],         description:'Duplicar selección' },
    { keys:['Ctrl','K'],         description:'Eliminar selección' },
    { keys:['Ctrl','Shift','E'], description:'Exportar múltiples archivos' },
    { keys:['Ctrl','B'],         description:'Añadir etiqueta en cursor' },
  ]},
  { program:'Adobe Audition', category:'audio', color:'#00005b', shortcuts:[
    { keys:['Espacio'],          description:'Play / Pausa' },
    { keys:['Shift','Espacio'],  description:'Reproducir desde el inicio' },
    { keys:['Ctrl','K'],         description:'Dividir clip' },
    { keys:['Shift','D'],        description:'Duplicar clip' },
    { keys:['Ctrl','Shift','K'], description:'Ripple Delete' },
    { keys:['G'],                description:'Agrupar clips' },
    { keys:['R'],                description:'Grabar' },
    { keys:['Ctrl','E'],         description:'Exportar archivo de audio' },
    { keys:['Ctrl','Shift','E'], description:'Exportar Multi-Track Mix' },
    { keys:['M'],                description:'Insertar marcador' },
    { keys:['Ctrl','Z'],         description:'Deshacer' },
    { keys:['Ctrl','Shift','M'], description:'Silenciar pista' },
    { keys:['F'],                description:'Zoom a selección' },
    { keys:['Ctrl','L'],         description:'Normalizar' },
  ]},
  { program:'Ableton Live', category:'audio', color:'#222', shortcuts:[
    { keys:['Tab'],              description:'Cambiar Session/Arrangement' },
    { keys:['Ctrl','D'],         description:'Duplicar' },
    { keys:['Ctrl','E'],         description:'Dividir clip' },
    { keys:['Ctrl','J'],         description:'Unir clips' },
    { keys:['Espacio'],          description:'Play / Pausa' },
    { keys:['Ctrl','Z'],         description:'Deshacer' },
    { keys:['Ctrl','R'],         description:'Exportar Audio' },
    { keys:['Ctrl','T'],         description:'Nueva pista de audio' },
    { keys:['Ctrl','Shift','T'], description:'Nueva pista MIDI' },
    { keys:['Ctrl','M'],         description:'Modo asignación MIDI' },
    { keys:['Ctrl','K'],         description:'Modo asignación de teclas' },
    { keys:['Ctrl','Shift','F'], description:'Follow (seguir cabezal)' },
    { keys:['Ctrl','I'],         description:'Insertar silencio' },
    { keys:['Shift','Tab'],      description:'Mostrar/ocultar clips' },
  ]},
  { program:'Logic Pro', category:'audio', color:'#1a1a1a', shortcuts:[
    { keys:['Cmd','T'],          description:'Dividir en el cabezal' },
    { keys:['Cmd','J'],          description:'Unir regiones' },
    { keys:['Espacio'],          description:'Play / Pausa' },
    { keys:['R'],                description:'Grabar' },
    { keys:['Cmd','A'],          description:'Seleccionar todo' },
    { keys:['Cmd','E'],          description:'Abrir editor de piano' },
    { keys:['X'],                description:'Mostrar/ocultar Mezclador' },
    { keys:['Cmd','R'],          description:'Exportar (Bounce)' },
    { keys:['Cmd','Shift','N'],  description:'Nueva pista de software' },
    { keys:['Cmd','Shift','A'],  description:'Nueva pista de audio' },
    { keys:['L'],                description:'Activar bucle de región' },
    { keys:['Cmd','U'],          description:'Quantizar notas MIDI' },
    { keys:['S'],                description:'Solo pista' },
    { keys:['M'],                description:'Silenciar pista' },
    { keys:['Cmd','K'],          description:'Teclado en pantalla' },
    { keys:['N'],                description:'Ver/ocultar ventana de notas' },
  ]},

  // ── 3D ─────────────────────────────────────────────────
  { program:'Blender', category:'3d', color:'#1a0e00', shortcuts:[
    { keys:['G'],                description:'Mover (Grab)' },
    { keys:['S'],                description:'Escalar' },
    { keys:['R'],                description:'Rotar' },
    { keys:['E'],                description:'Extruir' },
    { keys:['Tab'],              description:'Cambiar modo (Edit/Object)' },
    { keys:['Ctrl','B'],         description:'Bisel (Bevel)' },
    { keys:['Ctrl','R'],         description:'Loop Cut' },
    { keys:['I'],                description:'Insertar cara (Inset)' },
    { keys:['K'],                description:'Herramienta Knife (Cuchillo)' },
    { keys:['Alt','S'],          description:'Escalar en normales' },
    { keys:['H'],                description:'Ocultar selección' },
    { keys:['Alt','H'],          description:'Mostrar todo' },
    { keys:['Num7'],             description:'Vista superior' },
    { keys:['Num1'],             description:'Vista frontal' },
    { keys:['Num3'],             description:'Vista lateral derecha' },
    { keys:['Num5'],             description:'Ortogonal / Perspectiva' },
    { keys:['Shift','A'],        description:'Añadir objeto/malla' },
    { keys:['M'],                description:'Mover a colección' },
    { keys:['F12'],              description:'Renderizar frame' },
    { keys:['Ctrl','Alt','Num0'],description:'Alinear cámara a vista' },
  ]},
  { program:'Maya', category:'3d', color:'#0b1f22', shortcuts:[
    { keys:['Q'],                description:'Herramienta Selección' },
    { keys:['W'],                description:'Mover' },
    { keys:['E'],                description:'Rotar' },
    { keys:['R'],                description:'Escalar' },
    { keys:['F'],                description:'Enfocar objeto seleccionado' },
    { keys:['G'],                description:'Repetir última herramienta' },
    { keys:['3'],                description:'Vista suavizada (Smooth)' },
    { keys:['1'],                description:'Vista en cajas (Roughed)' },
    { keys:['4'],                description:'Vista Wireframe' },
    { keys:['5'],                description:'Vista Shaded' },
    { keys:['Ctrl','D'],         description:'Duplicar' },
    { keys:['Shift','D'],        description:'Duplicar con transformar' },
    { keys:['Ctrl','G'],         description:'Agrupar' },
    { keys:['Alt','clic'],       description:'Orbitar cámara' },
    { keys:['Alt','clic-medio'], description:'Paneo de cámara' },
  ]},
  { program:'Cinema 4D', category:'3d', color:'#001a3a', shortcuts:[
    { keys:['E'],                description:'Rotar' },
    { keys:['T'],                description:'Escalar' },
    { keys:['R'],                description:'Mover' },
    { keys:['C'],                description:'Convertir a Malla editable' },
    { keys:['F1'],               description:'Vista de perspectiva' },
    { keys:['F2'],               description:'Vista superior' },
    { keys:['F3'],               description:'Vista lateral derecha' },
    { keys:['F4'],               description:'Vista frontal' },
    { keys:['Ctrl','R'],         description:'Renderizar imagen' },
    { keys:['Shift','R'],        description:'Renderizar al Render Manager' },
    { keys:['A'],                description:'Seleccionar todo' },
    { keys:['U','L'],            description:'Selección Loop' },
    { keys:['M','S'],            description:'Herramienta Bisel' },
    { keys:['Ctrl','Z'],         description:'Deshacer' },
  ]},
  { program:'ZBrush', category:'3d', color:'#2a2a2a', shortcuts:[
    { keys:['X'],                description:'Simetría (eje X)' },
    { keys:['S'],                description:'Ajustar tamaño de pincel' },
    { keys:['I'],                description:'Ajustar intensidad' },
    { keys:['Ctrl','D'],         description:'Subdividir malla' },
    { keys:['Shift','F'],        description:'Mostrar polígonos (Polyframe)' },
    { keys:['D'],                description:'Nivel de subdivisión mayor' },
    { keys:['Shift','D'],        description:'Nivel de subdivisión menor' },
    { keys:['Q'],                description:'Modo Draw (esculpir)' },
    { keys:['W'],                description:'Modo Mover' },
    { keys:['E'],                description:'Modo Escalar' },
    { keys:['R'],                description:'Modo Rotar' },
    { keys:['Ctrl','Z'],         description:'Deshacer' },
    { keys:['Alt','clic'],       description:'Invertir máscara' },
    { keys:['Ctrl','Shift','clic'],description:'Aislar geometría visible' },
  ]},
  { program:'SketchUp', category:'3d', color:'#b22222', shortcuts:[
    { keys:['L'],                description:'Línea' },
    { keys:['P'],                description:'Push/Pull (Extruir)' },
    { keys:['R'],                description:'Rectángulo' },
    { keys:['M'],                description:'Mover' },
    { keys:['C'],                description:'Círculo' },
    { keys:['T'],                description:'Cinta métrica' },
    { keys:['S'],                description:'Escalar' },
    { keys:['Q'],                description:'Rotar' },
    { keys:['F'],                description:'Offset (Desfase de cara)' },
    { keys:['A'],                description:'Arco' },
    { keys:['E'],                description:'Borrar (Eraser)' },
    { keys:['G'],                description:'Crear Grupo/Componente' },
    { keys:['Z'],                description:'Zoom Extensión' },
    { keys:['K'],                description:'Mostrar sombras' },
  ]},
  { program:'BluffTitler', category:'3d', color:'#1c2e40', shortcuts:[
    { keys:['Espacio'],          description:'Play / Pausa' },
    { keys:['Ctrl','Z'],         description:'Deshacer' },
    { keys:['Ctrl','C'],         description:'Copiar capa' },
    { keys:['Ctrl','V'],         description:'Pegar capa' },
    { keys:['F5'],               description:'Exportar video' },
    { keys:['Ctrl','S'],         description:'Guardar proyecto' },
    { keys:['Delete'],           description:'Eliminar capa seleccionada' },
    { keys:['F1'],               description:'Vista frontal' },
    { keys:['F2'],               description:'Vista lateral' },
    { keys:['F3'],               description:'Vista superior' },
  ]},

  // ── INGENIERÍA ──────────────────────────────────────────
  { program:'AutoCAD', category:'engineering', color:'#cc0000', shortcuts:[
    { keys:['L','Enter'],        description:'Línea (Line)' },
    { keys:['TR','Enter'],       description:'Recortar (Trim)' },
    { keys:['EX','Enter'],       description:'Extender (Extend)' },
    { keys:['F8'],               description:'Modo Orto (líneas rectas)' },
    { keys:['F3'],               description:'Snap de objetos (Osnap)' },
    { keys:['F10'],              description:'Seguimiento polar' },
    { keys:['CO','Enter'],       description:'Copiar' },
    { keys:['M','Enter'],        description:'Mover' },
    { keys:['Z','E','Enter'],    description:'Zoom Extensión' },
    { keys:['O','Enter'],        description:'Desfase (Offset)' },
    { keys:['MI','Enter'],       description:'Espejo (Mirror)' },
    { keys:['REC','Enter'],      description:'Rectángulo' },
    { keys:['H','Enter'],        description:'Sombreado (Hatch)' },
    { keys:['AR','Enter'],       description:'Arreglo (Array)' },
    { keys:['DI','Enter'],       description:'Distancia entre dos puntos' },
    { keys:['LA','Enter'],       description:'Administrador de capas' },
    { keys:['PE','Enter'],       description:'Editar Polilínea' },
  ]},
  { program:'SolidWorks', category:'engineering', color:'#C0392B', shortcuts:[
    { keys:['S'],                description:'Atajos Inteligentes (S-key)' },
    { keys:['Ctrl','Q'],         description:'Reconstrucción Forzada' },
    { keys:['Ctrl','7'],         description:'Vista Isométrica' },
    { keys:['D'],                description:'Cota Inteligente' },
    { keys:['L'],                description:'Línea' },
    { keys:['C'],                description:'Círculo' },
    { keys:['F'],                description:'Zoom para ajustar' },
    { keys:['Ctrl','B'],         description:'Reconstruir modelo' },
    { keys:['Ctrl','S'],         description:'Guardar' },
    { keys:['Ctrl','Z'],         description:'Deshacer' },
    { keys:['Ctrl','1'],         description:'Vista frontal' },
    { keys:['Ctrl','2'],         description:'Vista trasera' },
    { keys:['Ctrl','3'],         description:'Vista izquierda' },
    { keys:['Ctrl','4'],         description:'Vista derecha' },
    { keys:['Ctrl','6'],         description:'Vista superior' },
    { keys:['G'],                description:'Lupa (Magnifying Glass)' },
  ]},
  { program:'Revit', category:'engineering', color:'#2B5796', shortcuts:[
    { keys:['W','A'],            description:'Crear Muro' },
    { keys:['D','R'],            description:'Crear Puerta' },
    { keys:['W','N'],            description:'Crear Ventana' },
    { keys:['A','L'],            description:'Alinear elementos' },
    { keys:['V','G'],            description:'Visibilidad / Gráficos' },
    { keys:['C','S'],            description:'Plano de Corte' },
    { keys:['D','I'],            description:'Cota inteligente' },
    { keys:['G','R'],            description:'Cuadrícula' },
    { keys:['R','P'],            description:'Plano de Referencia' },
    { keys:['M','M'],            description:'Espejo' },
    { keys:['R','O'],            description:'Rotar elemento' },
    { keys:['A','R'],            description:'Arreglo (Array)' },
    { keys:['Ctrl','Z'],         description:'Deshacer' },
    { keys:['Escape'],           description:'Cancelar comando' },
  ]},
  { program:'Matlab', category:'engineering', color:'#003f6b', shortcuts:[
    { keys:['Ctrl','Enter'],     description:'Ejecutar sección actual' },
    { keys:['F5'],               description:'Ejecutar todo el script' },
    { keys:['Ctrl','C'],         description:'Interrumpir ejecución' },
    { keys:['Tab'],              description:'Autocompletar' },
    { keys:['↑'],                description:'Comando anterior (historial)' },
    { keys:['Ctrl','R'],         description:'Comentar selección' },
    { keys:['Ctrl','T'],         description:'Descomentar selección' },
    { keys:['Ctrl','N'],         description:'Nuevo script' },
    { keys:['F10'],              description:'Step Over (depuración)' },
    { keys:['F11'],              description:'Step In (depuración)' },
    { keys:['Ctrl','D'],         description:'Ver documentación función' },
  ]},
  { program:'CATIA', category:'engineering', color:'#003087', shortcuts:[
    { keys:['F3'],               description:'Ocultar/mostrar árbol de entidades' },
    { keys:['H'],                description:'Ocultar/mostrar objeto' },
    { keys:['V'],                description:'Ver sólo seleccionado' },
    { keys:['Ctrl','U'],         description:'Actualizar cuerpo activo' },
    { keys:['Ctrl','Z'],         description:'Deshacer' },
    { keys:['Ctrl','W'],         description:'Ventana nueva' },
    { keys:['Escape'],           description:'Cancelar comando activo' },
    { keys:['Alt','clic'],       description:'Seleccionar oculto' },
    { keys:['Ctrl','PageUp'],    description:'Vista siguiente' },
    { keys:['Ctrl','PageDown'],  description:'Vista anterior' },
  ]},

  // ── MEDICINA ─────────────────────────────────────────────
  { program:'Anki', category:'medicine', shortcuts:[
    { keys:['Espacio'],          description:'Mostrar respuesta / Aprobar' },
    { keys:['1'],                description:'Otra vez (vuelve pronto)' },
    { keys:['2'],                description:'Difícil' },
    { keys:['3'],                description:'Bien' },
    { keys:['4'],                description:'Fácil' },
    { keys:['A'],                description:'Añadir tarjeta nueva' },
    { keys:['E'],                description:'Editar tarjeta actual' },
    { keys:['*'],                description:'Marcar tarjeta' },
    { keys:['Delete'],           description:'Eliminar tarjeta' },
    { keys:['Ctrl','Z'],         description:'Deshacer última acción' },
    { keys:['@'],                description:'Suspender tarjeta' },
    { keys:['!'],                description:'Marcar como fallida' },
    { keys:['Ctrl','F'],         description:'Buscar en el mazo' },
  ]},
  { program:'OsiriX / Horos', category:'medicine', shortcuts:[
    { keys:['M'],                description:'Herramienta Medición' },
    { keys:['Ctrl','L'],         description:'Ajuste de Ventana (W/L)' },
    { keys:['Ctrl','3'],         description:'Reconstrucción 3D' },
    { keys:['←','→'],            description:'Navegar entre series' },
    { keys:['↑','↓'],            description:'Navegar entre cortes' },
    { keys:['R'],                description:'Herramienta ROI' },
    { keys:['Shift','clic'],     description:'Añadir punto a ROI' },
    { keys:['Escape'],           description:'Deseleccionar herramienta' },
    { keys:['Ctrl','E'],         description:'Exportar imágenes' },
    { keys:['Cmd','I'],          description:'Info del paciente' },
  ]},
  { program:'Complete Anatomy', category:'medicine', shortcuts:[
    { keys:['R'],                description:'Rotar modelo 3D' },
    { keys:['F'],                description:'Buscar estructura anatómica' },
    { keys:['Espacio'],          description:'Ocultar/mostrar capas' },
    { keys:['+'],                description:'Añadir estructura a selección' },
    { keys:['-'],                description:'Quitar estructura de selección' },
    { keys:['Ctrl','Z'],         description:'Deshacer disección' },
    { keys:['A'],                description:'Vista anterior' },
    { keys:['P'],                description:'Vista posterior' },
    { keys:['S'],                description:'Vista superior' },
    { keys:['L'],                description:'Cambiar vista lateral' },
  ]},
  { program:'PubMed', category:'medicine', shortcuts:[
    { keys:['[tiab]'],           description:'Buscar en Título y Resumen' },
    { keys:['[MeSH]'],           description:'Buscar término MeSH exacto' },
    { keys:['[au]'],             description:'Filtrar por autor' },
    { keys:['[dp]'],             description:'Filtrar por fecha de publicación' },
    { keys:['[jour]'],           description:'Filtrar por revista' },
    { keys:['[pt]'],             description:'Filtrar por tipo de publicación' },
    { keys:['AND'],              description:'Operador booleano AND' },
    { keys:['OR'],               description:'Operador booleano OR' },
    { keys:['NOT'],              description:'Operador booleano NOT' },
    { keys:['"..."'],            description:'Búsqueda de frase exacta' },
    { keys:['*'],                description:'Truncamiento de término' },
  ]},

  // ── DEV / IT ─────────────────────────────────────────────
  { program:'VS Code', category:'dev', color:'#007ACC', shortcuts:[
    { keys:['Ctrl','P'],         description:'Ir a archivo (Go to File)' },
    { keys:['Ctrl','Shift','P'], description:'Paleta de comandos' },
    { keys:['Ctrl','`'],         description:'Abrir Terminal integrado' },
    { keys:['Ctrl','Shift','`'], description:'Nueva terminal' },
    { keys:['Alt','Shift','F'],  description:'Formatear documento' },
    { keys:['F2'],               description:'Renombrar símbolo' },
    { keys:['Ctrl','/'],         description:'Comentar/Descomentar línea' },
    { keys:['Ctrl','D'],         description:'Seleccionar siguiente ocurrencia' },
    { keys:['Ctrl','Shift','L'], description:'Seleccionar todas las ocurrencias' },
    { keys:['Alt','↑/↓'],        description:'Mover línea arriba/abajo' },
    { keys:['Ctrl','Shift','K'], description:'Eliminar línea' },
    { keys:['F12'],              description:'Ir a definición' },
    { keys:['Ctrl','B'],         description:'Mostrar/ocultar Sidebar' },
    { keys:['Ctrl','G'],         description:'Ir a línea' },
    { keys:['Ctrl','H'],         description:'Buscar y reemplazar' },
    { keys:['Ctrl','Shift','F'], description:'Buscar en todos los archivos' },
    { keys:['Ctrl','\\'],        description:'Dividir editor' },
    { keys:['Alt','Shift','↑'],  description:'Copiar línea arriba' },
    { keys:['Ctrl','K','Ctrl','S'],description:'Ver atajos de teclado' },
    { keys: ['Ctrl','P'], description: 'Buscar archivos rápido' },
    { keys: ['Ctrl','Shift','P'], description: 'Command Palette' },
    { keys: ['Ctrl','B'], description: 'Toggle sidebar' },
    { keys: ['Alt','↑','↓'], description: 'Mover línea' },
    { keys: ['Shift','Alt','↓'], description: 'Duplicar línea' },
    { keys: ['Ctrl','/'], description: 'Comentar línea' },
    { keys: ['Ctrl','D'], description: 'Seleccionar coincidencia' },
    { keys: ['Ctrl','Shift','L'], description: 'Seleccionar todas las coincidencias' },
  ]},
  { program:'Terminal (Linux/Mac)', category:'dev', color:'#1a1a1a', shortcuts:[
    { keys:['Ctrl','C'],         description:'Interrumpir proceso actual' },
    { keys:['Ctrl','Z'],         description:'Suspender proceso (background)' },
    { keys:['Ctrl','D'],         description:'Cerrar sesión / EOF' },
    { keys:['Ctrl','L'],         description:'Limpiar pantalla' },
    { keys:['Ctrl','R'],         description:'Buscar en historial' },
    { keys:['Tab'],              description:'Autocompletar' },
    { keys:['↑','↓'],            description:'Navegar historial de comandos' },
    { keys:['Ctrl','A'],         description:'Ir al inicio de la línea' },
    { keys:['Ctrl','E'],         description:'Ir al final de la línea' },
    { keys:['Ctrl','U'],         description:'Borrar desde cursor al inicio' },
    { keys:['Ctrl','K'],         description:'Borrar desde cursor al final' },
    { keys:['Ctrl','W'],         description:'Borrar palabra anterior' },
    { keys:['Alt','B'],          description:'Mover cursor una palabra atrás' },
    { keys:['Alt','F'],          description:'Mover cursor una palabra adelante' },
    { keys:['!!'],               description:'Repetir último comando' },
  ]},
  { program:'CMD (Windows)', category:'dev', color:'#012456', shortcuts:[
    { keys:['↑','↓'],            description:'Navegar historial de comandos' },
    { keys:['Tab'],              description:'Autocompletar nombre de archivo' },
    { keys:['Ctrl','C'],         description:'Cancelar proceso en ejecución' },
    { keys:['Ctrl','A'],         description:'Seleccionar todo el texto' },
    { keys:['Ctrl','F'],         description:'Buscar texto en la consola' },
    { keys:['F7'],               description:'Ver historial de comandos' },
    { keys:['cls'],              description:'Limpiar pantalla (comando)' },
    { keys:['Alt','Enter'],      description:'Pantalla completa / ventana' },
    { keys:['F3'],               description:'Repetir último comando' },
    { keys:['Ctrl','M'],         description:'Modo marcación (para copiar)' },
  ]},
  { program:'Wireshark', category:'dev', color:'#1e5da3', shortcuts:[
    { keys:['Ctrl','K'],         description:'Iniciar captura' },
    { keys:['Ctrl','E'],         description:'Detener captura' },
    { keys:['Ctrl','F'],         description:'Buscar paquete' },
    { keys:['Ctrl','G'],         description:'Ir a paquete por número' },
    { keys:['Ctrl','R'],         description:'Recargar archivo de captura' },
    { keys:['Ctrl','D'],         description:'Marcar/Desmarcar paquete' },
    { keys:['Ctrl','Shift','N'], description:'Siguiente paquete marcado' },
    { keys:['Ctrl','M'],         description:'Aplicar como filtro seleccionado' },
    { keys:['Ctrl','T'],         description:'Seguir stream TCP' },
    { keys:['Ctrl','N'],         description:'Próximo paquete en conversación' },
    { keys:['Ctrl','B'],         description:'Paquete previo en conversación' },
  ]},
  { program:'Zabbix (Web UI)', category:'dev', color:'#d40000', shortcuts:[
    { keys:['Alt','A'],          description:'Ir a Alertas' },
    { keys:['Alt','D'],          description:'Ir a Dashboard' },
    { keys:['Alt','M'],          description:'Ir a Monitorización' },
    { keys:['Alt','P'],          description:'Ir a Problemas activos' },
    { keys:['Ctrl','F'],         description:'Buscar host en tabla' },
    { keys:['F5'],               description:'Refrescar vista actual' },
    { keys:['?'],                description:'Ver atajos disponibles' },
  ]},

  // ── OFIMÁTICA ────────────────────────────────────────────
  { program:'Excel', category:'office', color:'#1e6f3e', shortcuts:[
    { keys:['Ctrl','G'],          description:'Guardar' },
    { keys:['F12'],               description:'Guardar como' },
    { keys:['Ctrl','P'],          description:'Imprimir' },
    { keys:['Ctrl','Z'],          description:'Deshacer' },
    { keys:['Ctrl','Y'],          description:'Rehacer' },
    { keys:['Ctrl','C'],          description:'Copiar' },
    { keys:['Ctrl','X'],          description:'Cortar' },
    { keys:['Ctrl','V'],          description:'Pegar' },
    { keys:['Ctrl','T'],          description:'Crear Tabla' },
    { keys:['Ctrl','Shift','L'],  description:'Filtro automático' },
    { keys:['Alt','='],           description:'Autosuma' },
    { keys:['F2'],                description:'Editar celda activa' },
    { keys:['F4'],                description:'Referencia absoluta ($A$1) / Repetir' },
    { keys:['Ctrl','Shift','Enter'], description:'Fórmula matricial' },
    { keys:['Ctrl',';'],          description:'Insertar fecha de hoy' },
    { keys:['Ctrl','Shift',';'],  description:'Insertar hora actual' },
    { keys:['Ctrl','PageDown'],   description:'Ir a hoja siguiente' },
    { keys:['Ctrl','PageUp'],     description:'Ir a hoja anterior' },
    { keys:['Ctrl','1'],          description:'Formato de Celdas' },
    { keys:['Ctrl','N'],          description:'Aplicar Negrita' },
    { keys:['Ctrl','K'],          description:'Aplicar Cursiva' },
    { keys:['Ctrl','S'],          description:'Aplicar Subrayado' },
    { keys:['Ctrl','Shift','$'],  description:'Formato Moneda' },
    { keys:['Ctrl','Shift','%'],  description:'Formato Porcentaje' },
    { keys:['Alt','F8'],          description:'Abrir Macros' },
    { keys:['F11'],               description:'Insertar gráfico en nueva hoja' },
    { keys:['Ctrl','Shift','End'],description:'Ir al último dato' },
    { keys:['Ctrl','Home'],       description:'Ir a la celda A1' },
    { keys:['Ctrl','Shift','↓'],  description:'Seleccionar hasta el último dato' },
    { keys:['Alt','Enter'],       description:'Salto de línea dentro de celda' },
    { keys:['Ctrl','D'],          description:'Copiar celda de arriba' },
    { keys:['Ctrl','Shift','U'],  description:'Expandir barra de fórmulas' },
    { keys:['Alt','F8'],          description:'Abrir editor de Macros' },
  ]},
  { program:'Word', category:'office', color:'#2b579a', shortcuts:[
    { keys:['Ctrl','G'],          description:'Guardar' },
    { keys:['F12'],               description:'Guardar como' },
    { keys:['Ctrl','P'],          description:'Imprimir' },
    { keys:['Ctrl','Z'],          description:'Deshacer' },
    { keys:['Ctrl','Y'],          description:'Rehacer' },
    { keys:['Ctrl','C'],          description:'Copiar' },
    { keys:['Ctrl','X'],          description:'Cortar' },
    { keys:['Ctrl','V'],          description:'Pegar' },
    { keys:['Ctrl','N'],          description:'Aplicar Negrita' },
    { keys:['Ctrl','K'],          description:'Aplicar Cursiva' },
    { keys:['Ctrl','S'],          description:'Aplicar Subrayado' },
    { keys:['Ctrl','E'],          description:'Centrar párrafo' },
    { keys:['Ctrl','J'],          description:'Justificar párrafo' },
    { keys:['Ctrl','Q'],          description:'Alinear a la izquierda' },
    { keys:['Ctrl','D'],          description:'Alinear a la derecha' },
    { keys:['Ctrl','T'],          description:'Sangría francesa' },
    { keys:['Ctrl','Alt','1'],    description:'Aplicar Título 1' },
    { keys:['Ctrl','Alt','2'],    description:'Aplicar Título 2' },
    { keys:['Ctrl','Alt','3'],    description:'Aplicar Título 3' },
    { keys:['Ctrl','Shift','N'],  description:'Aplicar estilo Normal' },
    { keys:['Ctrl','B'],          description:'Insertar hipervínculo' },
    { keys:['Ctrl','H'],          description:'Buscar y Reemplazar' },
    { keys:['Ctrl','F'],          description:'Buscar' },
    { keys:['F5'],                description:'Ir a (página, sección…)' },
    { keys:['F7'],                description:'Revisar ortografía' },
    { keys:['Shift','F3'],        description:'Cambiar mayúsculas/minúsculas' },
    { keys:['Ctrl','Shift','C'],  description:'Copiar formato' },
    { keys:['Ctrl','Shift','V'],  description:'Pegar formato' },
    { keys:['Ctrl','Shift','8'],  description:'Ver marcas de formato' },
    { keys:['Ctrl','['],          description:'Reducir tamaño de fuente' },
    { keys:['Ctrl',']'],          description:'Aumentar tamaño de fuente' },
    { keys:['Ctrl','Q'],          description:'Quitar formato de párrafo' },
    { keys:['Ctrl','Alt','S'],    description:'Dividir ventana' },
  ]},
  { program:'PowerPoint', category:'office', color:'#b7472a', shortcuts:[
    { keys:['Ctrl','G'],          description:'Guardar' },
    { keys:['F12'],               description:'Guardar como' },
    { keys:['Ctrl','P'],          description:'Imprimir' },
    { keys:['Ctrl','Z'],          description:'Deshacer' },
    { keys:['Ctrl','Y'],          description:'Rehacer' },
    { keys:['Ctrl','C'],          description:'Copiar' },
    { keys:['Ctrl','X'],          description:'Cortar' },
    { keys:['Ctrl','V'],          description:'Pegar' },
    { keys:['Ctrl','N'],          description:'Aplicar Negrita' },
    { keys:['Ctrl','K'],          description:'Aplicar Cursiva' },
    { keys:['Ctrl','S'],          description:'Aplicar Subrayado' },
    { keys:['F5'],                description:'Presentación desde el inicio' },
    { keys:['Shift','F5'],        description:'Presentación desde diapositiva actual' },
    { keys:['Alt','F5'],          description:'Vista del presentador' },
    { keys:['Escape'],            description:'Finalizar presentación' },
    { keys:['B'],                 description:'Pantalla negra (durante presentación)' },
    { keys:['W'],                 description:'Pantalla blanca (durante presentación)' },
    { keys:['→','N','Enter'],     description:'Siguiente diapositiva' },
    { keys:['←','P'],             description:'Diapositiva anterior' },
    { keys:['Ctrl','M'],          description:'Nueva diapositiva' },
    { keys:['Ctrl','D'],          description:'Duplicar diapositiva/objeto' },
    { keys:['Ctrl','G'],          description:'Agrupar objetos' },
    { keys:['Ctrl','Shift','G'],  description:'Desagrupar objetos' },
    { keys:['Tab'],               description:'Seleccionar siguiente objeto' },
    { keys:['Ctrl','Enter'],      description:'Siguiente marcador de posición' },
    { keys:['Ctrl','Shift','<'],  description:'Reducir tamaño de fuente' },
    { keys:['Ctrl','Shift','>'],  description:'Aumentar tamaño de fuente' },
    { keys:['Alt','Shift','→'],   description:'Aumentar nivel de lista' },
    { keys:['Alt','Shift','←'],   description:'Reducir nivel de lista' },
  ]},
  { program:'Notion', category:'office', color:'#f0efe9', shortcuts:[
    { keys:['/'],                description:'Abrir menú de bloques' },
    { keys:['Ctrl','\\'],        description:'Ocultar/mostrar Sidebar' },
    { keys:['Ctrl','P'],         description:'Búsqueda global' },
    { keys:['Ctrl','Shift','L'], description:'Modo oscuro / claro' },
    { keys:['Ctrl','Enter'],     description:'Abrir página seleccionada' },
    { keys:['Ctrl','D'],         description:'Duplicar bloque' },
    { keys:['Ctrl','Shift','M'], description:'Comentar selección' },
    { keys:['[ ]'],              description:'Casilla To-do' },
    { keys:['Ctrl','Shift','H'], description:'Resaltar texto (highlight)' },
    { keys:['Ctrl','Shift','S'], description:'Añadir a favoritos' },
    { keys:['Ctrl','Shift','1'], description:'Título H1' },
    { keys:['Ctrl','Shift','2'], description:'Título H2' },
    { keys:['Ctrl','Shift','9'], description:'Bloque de código' },
    { keys:['Ctrl','Shift','4'], description:'Lista con viñetas' },
    { keys:['Ctrl','Shift','5'], description:'Lista numerada' },
  ]},
  { program:'Slack', category:'office', color:'#4a154b', shortcuts:[
    { keys:['Ctrl','K'],         description:'Cambiar de canal / DM (Jump)' },
    { keys:['Ctrl','Shift','K'], description:'Abrir Mensajes Directos' },
    { keys:['Alt','↑/↓'],        description:'Canal anterior / siguiente' },
    { keys:['Shift','Enter'],    description:'Nueva línea en mensaje' },
    { keys:['Ctrl','/'],         description:'Ver todos los atajos' },
    { keys:['Ctrl','F'],         description:'Buscar en workspace' },
    { keys:['Ctrl','Shift','\\'],description:'Reaccionar con emoji' },
    { keys:['Ctrl','Shift','A'], description:'Todos los hilos no leídos' },
    { keys:['Ctrl','U'],         description:'Subir archivo' },
    { keys:['Ctrl','Shift','Y'], description:'Establecer estado' },
    { keys:['Ctrl','Shift','T'], description:'Ver hilos' },
    { keys:['↑'],                description:'Editar último mensaje enviado' },
    { keys:['Ctrl','.'],         description:'Panel derecho' },
  ]},

  // ── STREAMING ─────────────────────────────────────────────
  { program:'OBS Studio', category:'streaming', color:'#1a1a2e', shortcuts:[
    { keys:['Ctrl','Shift','S'], description:'Iniciar / Detener Stream' },
    { keys:['Ctrl','Shift','R'], description:'Iniciar / Detener Grabación' },
    { keys:['Ctrl','Shift','P'], description:'Pausar grabación' },
    { keys:['Ctrl','Shift','M'], description:'Silenciar micrófono' },
    { keys:['Ctrl','M'],         description:'Silenciar audio de escritorio' },
    { keys:['F7'],               description:'Activar Studio Mode' },
    { keys:['Ctrl','Shift','F'], description:'Fuente en Pantalla Completa' },
    { keys:['Ctrl','1'],         description:'Cambiar a Escena 1' },
    { keys:['Ctrl','2'],         description:'Cambiar a Escena 2' },
    { keys:['Ctrl','3'],         description:'Cambiar a Escena 3' },
    { keys:['Ctrl','T'],         description:'Activar Cámara Virtual' },
    { keys:['Ctrl','Shift','B'], description:'Transición Start/Stop' },
  ]},
  { program:'Streamlabs', category:'streaming', color:'#09aaef', shortcuts:[
    { keys:['Ctrl','Shift','S'], description:'Iniciar / Detener Stream' },
    { keys:['Ctrl','Shift','R'], description:'Iniciar / Detener Grabación' },
    { keys:['Ctrl','T'],         description:'Cambiar a Escena siguiente' },
    { keys:['Alt','A'],          description:'Silenciar / activar Audio' },
    { keys:['Ctrl','D'],         description:'Abrir chat de donaciones' },
    { keys:['Ctrl','M'],         description:'Silenciar micrófono' },
    { keys:['Ctrl','1'],         description:'Escena 1' },
    { keys:['Ctrl','2'],         description:'Escena 2' },
    { keys:['Ctrl','Shift','T'], description:'Activar Cámara Virtual' },
  ]},
]; // ← Fin del array. Añade nuevos programas antes de este cierre.
